"""Declarative shim — generated connection method lives in generated/capabilities."""

from freecad_mcp.generated.capabilities.connection_methods.connection_view_ops import (
    activate_document,
    animate_placement,
    capture_view_sequence,
    capture_view_sequence_to_disk,
    get_active_screenshot,
    get_gui_state,
    get_object,
    get_objects,
    get_parts_list,
    get_selection,
    list_documents,
    open_document,
    recompute_and_wait,
    refresh_view,
    repair_view_placements,
    select_subshapes,
    set_section_view,
    set_tree_expanded,
)

__all__ = [
    'activate_document',
    'animate_placement',
    'capture_view_sequence',
    'capture_view_sequence_to_disk',
    'get_active_screenshot',
    'get_gui_state',
    'get_object',
    'get_objects',
    'get_parts_list',
    'get_selection',
    'list_documents',
    'open_document',
    'recompute_and_wait',
    'refresh_view',
    'repair_view_placements',
    'select_subshapes',
    'set_section_view',
    'set_tree_expanded',
]
