"""Declarative shim — generated connection method lives in generated/capabilities."""

from freecad_mcp.generated.capabilities.connection_methods.connection_read_ops import (
    cancel_worker_job,
    check_rpc_sync,
    create_document,
    create_object,
    delete_object,
    edit_object,
    execute_code,
    execute_code_async,
    get_instance_info,
    get_worker_status,
    insert_part_from_library,
    inspect_references,
    ping,
    reload_document,
    repair_references,
    supports_rpc_parameter,
    verify_instance,
)

__all__ = [
    'cancel_worker_job',
    'check_rpc_sync',
    'create_document',
    'create_object',
    'delete_object',
    'edit_object',
    'execute_code',
    'execute_code_async',
    'get_instance_info',
    'get_worker_status',
    'insert_part_from_library',
    'inspect_references',
    'ping',
    'reload_document',
    'repair_references',
    'supports_rpc_parameter',
    'verify_instance',
]
