"""Capability manifest for partdesign (bootstrapped)."""

from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="partdesign",
    register_modules=('tools_partdesign_a', 'tools_partdesign_a2', 'tools_partdesign_b', 'tools_partdesign_b2'),
    tools=(
        ToolEntry(
            name="create_datum_plane",
            docstring="Create a PartDesign datum plane for assembly reference workflows.\n\nRecipes (avoid the silent P1/P3 traps):\n  * **XY_Plane + AttachmentOffset instead of a rotated datum.** Prefer\n    attaching to an origin ``XY_Plane``/``XZ_Plane``/``YZ_Plane`` and using\n    ``offset_along_normal`` + ``AttachmentOffset`` to position the plane,\n    rather than creating a datum on a default axis and then rotating its\n    Placement. A rotated ``Deactivated`` datum can drop the rotation (P3).\n  * **Identity-body rebuild for cross-body datums.** When a datum in Body A\n    must reference a face in Body B, keep Body B at an identity placement\n    (move the geometry into Body B via a pad/transform instead of moving the\n    body). FreeCAD's attacher can drop a non-identity source-body placement\n    (P1). Use ``preview_attachment`` to confirm, and ``placement_audit`` to\n    find risk concentrations.",
            signature='(ctx: \'Context\', doc_name: \'str\', plane_name: \'str\', body_name: \'str\', mode: "Literal[\'midpoint_between_faces\', \'through_point\', \'offset_from_face\', \'between_parallel_planes\', \'plane_from_binder_face\']", source_ref: \'str | None\' = None, face_a: \'str | None\' = None, face_b: \'str | None\' = None, offset_along_normal: \'list[float] | None\' = None, map_mode: \'str\' = \'FlatFace\', if_exists: "Literal[\'error\', \'skip\', \'replace\']" = \'error\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.create_datum_plane_operation",
            rpc_method="create_datum_plane",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_a",
        ),
        ToolEntry(
            name="create_part_container",
            docstring='Create an App::Part assembly container.',
            signature='(ctx: \'Context\', doc_name: \'str\', part_name: \'str\', parent_container: \'str | None\' = None, if_exists: "Literal[\'error\', \'skip\', \'replace\']" = \'error\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.create_part_container_operation",
            rpc_method="create_part_container",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_a",
        ),
        ToolEntry(
            name="create_subshape_binder",
            docstring='Create a PartDesign SubShapeBinder with placement validation.',
            signature='(ctx: \'Context\', doc_name: \'str\', binder_name: \'str\', source_object: \'str\', sub_elements: \'list[str] | None\' = None, target_body: \'str | None\' = None, target_container: \'str | None\' = None, relative: \'bool\' = False, sync_placement: \'bool\' = True, if_exists: "Literal[\'error\', \'skip\', \'replace\']" = \'error\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.create_subshape_binder_operation",
            rpc_method="create_subshape_binder",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_a",
        ),
        ToolEntry(
            name="move_object",
            docstring='Move an object into a PartDesign Body or App::Part container.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str', target_container: 'str', remove_from_old_parent: 'bool' = True) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.move_object_operation",
            rpc_method="move_object",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_a",
        ),
        ToolEntry(
            name="build_path_wire",
            docstring='Build a Part wire from sketch geometry and optional bridge segments.',
            signature='(ctx: \'Context\', doc_name: \'str\', wire_name: \'str\', segments: \'list[dict[str, Any]]\', tolerance_mm: \'float\' = 0.5, container: \'str | None\' = None, if_exists: "Literal[\'error\', \'skip\', \'replace\']" = \'error\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.build_path_wire_operation",
            rpc_method="build_path_wire",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_a2",
        ),
        ToolEntry(
            name="get_sketch_geometry",
            docstring='Return sketch geometry endpoints, construction flags, constraints, and external refs.',
            signature="(ctx: 'Context', doc_name: 'str', sketch_name: 'str', include_constraints: 'bool' = True, include_external: 'bool' = True, global_coords: 'bool' = True) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_sketch_geometry_operation",
            rpc_method="get_sketch_geometry",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_partdesign_a2",
        ),
        ToolEntry(
            name="sketch_add_external_projection",
            docstring="Add external geometry to a sketch with assembly-aware preflight checks.\n\nSet ``allow_gui_geometry_loop=True`` to explicitly run the bounded preflight\nand projection mutation on FreeCAD's GUI thread. The default is false\nbecause the static geometry-loop guard cannot prove this generated\npreflight is bounded.",
            signature='(ctx: \'Context\', doc_name: \'str\', sketch_name: \'str\', source_ref: \'str\', projection_mode: "Literal[\'auto\', \'edge\', \'face\', \'point\']" = \'auto\', defining: \'bool\' = False, allow_gui_geometry_loop: \'bool\' = False) -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.sketch_add_external_projection_operation",
            rpc_method="sketch_add_external_projection",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=True,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_a2",
        ),
        ToolEntry(
            name="sweep_pipe",
            docstring='Sweep a circular solid pipe along a wire path.',
            signature='(ctx: \'Context\', doc_name: \'str\', path_wire: \'str\', diameter_mm: \'float\', solid_name: \'str\', profile_mode: \'str\' = \'frenet\', color: \'list[float] | None\' = None, container: \'str | None\' = None, if_exists: "Literal[\'error\', \'skip\', \'replace\']" = \'error\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.sweep_pipe_operation",
            rpc_method="sweep_pipe",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_a2",
        ),
        ToolEntry(
            name="face_normal",
            docstring='Return the global normal (and centre) of a face (M6 / P8 guard).\n\nDerives the vector from the face geometry via ``normalAt`` rotated by the\nobject\'s global placement, avoiding the Direction-vs-Axis trap. Returns JSON\n``{ok, object, subshape, type, global_center, global_normal, radius}``.\n\nArgs:\n    doc_name: The document containing the object.\n    object_name: The object whose face to inspect.\n    face: The face name, e.g. ``"Face3"``.',
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str', face: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.face_normal_operation",
            rpc_method="face_normal",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_partdesign_b",
        ),
        ToolEntry(
            name="find_edges",
            docstring="Find edges of an object by geometry — removes edge-index fragility (I4).\n\nReturns a ranked JSON list of edges matching the criteria, each with its\nglobal centre, global direction, length and radius. E.g. find the circular\nedge of radius 5 on top of a cylinder with\n``type='Circle', radius=5, center_approx={'x':0,'y':0,'z':10}``.\n\nArgs:\n    doc_name: The document containing the object.\n    object_name: The object whose edges to search.\n    type: Optional curve type filter: 'Line', 'Circle', 'Ellipse',\n        'BSplineCurve'.\n    direction_approx: Optional vector; edges whose axis is parallel to this\n        within ``tol`` are kept (use for line edges).\n    center_approx: Optional point; edges whose global centre is within\n        ``center_tol`` mm are kept, results ranked by closeness.\n    radius: Optional radius; circular/elliptical edges within ``tol`` are kept.\n    tol: Parallelism and radius tolerance (default 1e-3).\n    center_tol: Centre proximity tolerance in mm (default 1.0).\n    limit: Maximum number of results (default 10).",
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str', type: 'str | None' = None, direction_approx: 'dict | list | None' = None, center_approx: 'dict | list | None' = None, radius: 'float | None' = None, tol: 'float' = 0.001, center_tol: 'float' = 1.0, limit: 'int' = 10) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.find_edges_operation",
            rpc_method="find_edges",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_partdesign_b",
        ),
        ToolEntry(
            name="find_faces",
            docstring='Find faces of an object by geometry — removes face-index fragility (I4).\n\nReturns a ranked JSON list of faces matching the criteria, each with its\nglobal centre, global normal, area and radius. Ask for "the top planar face"\n(``type=\'Plane\', normal_approx={\'x\':0,\'y\':0,\'z\':1}``) instead of guessing\n``Face6``.\n\nArgs:\n    doc_name: The document containing the object.\n    object_name: The object whose faces to search.\n    type: Optional surface type filter: \'Plane\', \'Cylinder\', \'Cone\',\n        \'Sphere\', \'Toroid\'.\n    normal_approx: Optional {\'x\',\'y\',\'z\'} (or [x,y,z]) vector; faces whose\n        normal is parallel to this within ``tol`` are kept.\n    center_approx: Optional point; faces whose global centre is within\n        ``center_tol`` mm of it are kept, and results are ranked by closeness.\n    radius: Optional radius; cylindrical/spherical faces within ``tol`` are kept.\n    tol: Parallelism and radius tolerance (default 1e-3).\n    center_tol: Centre proximity tolerance in mm (default 1.0).\n    limit: Maximum number of results (default 10).',
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str', type: 'str | None' = None, normal_approx: 'dict | list | None' = None, center_approx: 'dict | list | None' = None, radius: 'float | None' = None, tol: 'float' = 0.001, center_tol: 'float' = 1.0, limit: 'int' = 10) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.find_faces_operation",
            rpc_method="find_faces",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_partdesign_b",
        ),
        ToolEntry(
            name="preview_attachment",
            docstring="Preview an existing datum's attachment — a read-only P1 diagnostic.\n\nReports the support reference, the support face/edge global centre and\nnormal, the datum's global base/normal, the owning bodies and their\nplacements, ``source_body_placement_dropped`` (True when the support lives\nin a different body with a non-identity placement — the cross-body\nattachment drop risk), and a signed distance + normal-angle diff between the\ndatum and its support.\n\nUse this BEFORE building geometry on a cross-body datum, and to debug a\ndatum that landed in the wrong place, instead of rebuilding the model.\n\nArgs:\n    doc_name: The document containing the datum.\n    datum_name: The name of the datum (PartDesign::Plane/Line/Point, or any\n        object with an AttachmentSupport) to inspect.",
            signature="(ctx: 'Context', doc_name: 'str', datum_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.preview_attachment_operation",
            rpc_method="preview_attachment",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_b",
        ),
        ToolEntry(
            name="create_placement_binder",
            docstring='Create a SubShapeBinder using a body subpath with placement diagnostics (M6).\n\n``source`` should be a body subpath such as ``MG996RHornRef.HornHubPad.Face3``.\nReturns resolved source/binder local and global centers/normals and whether\nparent-body placement was dropped.',
            signature="(ctx: 'Context', doc_name: 'str', owner_body: 'str', name: 'str', source: 'str', relative: 'bool' = True, bind_mode: 'str' = 'Synchronized') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.create_placement_binder_operation",
            rpc_method="create_placement_binder",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_b2",
        ),
        ToolEntry(
            name="create_placement_datum",
            docstring='Create a datum plane from a body subpath with local/global diagnostics (M6).',
            signature="(ctx: 'Context', doc_name: 'str', owner_body: 'str', name: 'str', source: 'str', relative: 'bool' = True, offset: 'list[float] | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.create_placement_datum_operation",
            rpc_method="create_placement_datum",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_partdesign_b2",
        ),
        ToolEntry(
            name="edge_axis",
            docstring='Return the global axis/direction (and centre) of an edge (M6 / P8 guard).\n\nDerives the vector from the curve geometry rotated by the object\'s global\nplacement. Returns JSON\n``{ok, object, subshape, type, global_center, global_normal, radius}``.\n\nArgs:\n    doc_name: The document containing the object.\n    object_name: The object whose edge to inspect.\n    edge: The edge name, e.g. ``"Edge2"``.',
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str', edge: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.edge_axis_operation",
            rpc_method="edge_axis",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_partdesign_b2",
        ),
        ToolEntry(
            name="placement_audit",
            docstring="Audit placements per Body/Part (M3).\n\nLists each Body/Part's ``Placement``, ``getGlobalPlacement()`` base, and the\ncross-body datums that reference it. Use to spot P1 risk concentrations and\nplacement/geometry disagreements. Returns JSON\n``{ok, doc, bodies: [{name, type, placement_base, placement_rotation,\nglobal_placement_base, cross_body_datums}]}``.\n\nArgs:\n    doc_name: The document to audit.",
            signature="(ctx: 'Context', doc_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.placement_audit_operation",
            rpc_method="placement_audit",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_partdesign_b2",
        ),
    ),
)
