"""Capability manifest for features (bootstrapped)."""

# ruff: noqa: E501
from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="features",
    register_modules=('tools_features_advanced_a', 'tools_features_advanced_b', 'tools_features_basic_1', 'tools_features_basic_2', 'tools_features_boolean'),
    tools=(
        ToolEntry(
            name="loft_feature",
            docstring='Loft through two or more sketch sections (PartDesign::AdditiveLoft).\n\nArgs:\n    doc_name: Document containing the sketches and body.\n    sketch_names: Ordered list of sketch names to loft through (minimum 2).\n    loft_name: Name for the resulting Loft feature.\n    body_name: Optional explicit PartDesign Body name.\n    ruled: If true, use straight (ruled) lofting instead of smooth.\n    closed: If true, close the loft back to the first section.\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', sketch_names: 'list[str]', loft_name: 'str', body_name: 'str | None' = None, ruled: 'bool' = False, closed: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.loft_feature_operation",
            rpc_method="loft_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_advanced_a",
        ),
        ToolEntry(
            name="revolve_feature",
            docstring='Revolve a closed sketch profile around an axis (PartDesign::Revolution).\n\nArgs:\n    doc_name: Document containing the sketch and body.\n    sketch_name: Name of the sketch to revolve.\n    revolve_name: Name for the resulting Revolution feature.\n    angle: Revolution angle in degrees (default 360 = full solid of revolution).\n    axis: Revolution axis. Examples: ``Z_Axis``, ``X_Axis``, ``ObjectName:Edge1``.\n    body_name: Optional explicit PartDesign Body name.\n    symmetric: If true, revolve symmetrically about the sketch plane.\n    reversed_dir: If true, reverse the revolution direction.\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', sketch_name: 'str', revolve_name: 'str', angle: 'float' = 360.0, axis: 'str' = 'Z_Axis', body_name: 'str | None' = None, symmetric: 'bool' = False, reversed_dir: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.revolve_feature_operation",
            rpc_method="revolve_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_advanced_a",
        ),
        ToolEntry(
            name="sweep_feature",
            docstring='Sweep a profile sketch along a path sketch (PartDesign::AdditivePipe).\n\nArgs:\n    doc_name: Document containing the sketches and body.\n    profile_sketch: Name of the cross-section sketch.\n    path_sketch: Name of the path sketch.\n    sweep_name: Name for the resulting Sweep feature.\n    body_name: Optional explicit PartDesign Body name.\n    frenet: If true, use Frenet-Serret frame (avoids twisting on curved paths).\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', profile_sketch: 'str', path_sketch: 'str', sweep_name: 'str', body_name: 'str | None' = None, frenet: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.sweep_feature_operation",
            rpc_method="sweep_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_advanced_a",
        ),
        ToolEntry(
            name="chamfer_feature",
            docstring='Add a chamfer to edges of an existing solid (PartDesign::Chamfer).\n\nArgs:\n    doc_name: Document containing the body and feature.\n    base_feature: Name of the feature to chamfer.\n    chamfer_name: Name for the resulting Chamfer feature.\n    size: Chamfer size in mm (must be > 0).\n    edge_refs: Optional list of edge references like ``["Edge1","Edge3"]``.\n        If omitted, all edges are chamfered.\n    body_name: Optional explicit PartDesign Body name.\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', base_feature: 'str', chamfer_name: 'str', size: 'float', edge_refs: 'list[str] | None' = None, body_name: 'str | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.chamfer_feature_operation",
            rpc_method="chamfer_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_advanced_b",
        ),
        ToolEntry(
            name="fillet_feature",
            docstring='Add a fillet to edges of an existing solid (PartDesign::Fillet).\n\nArgs:\n    doc_name: Document containing the body and feature.\n    base_feature: Name of the feature to fillet.\n    fillet_name: Name for the resulting Fillet feature.\n    radius: Fillet radius in mm (must be > 0).\n    edge_refs: Optional list of edge references like ``["Edge1","Edge3"]``.\n        If omitted, all edges are filleted.\n    body_name: Optional explicit PartDesign Body name.\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', base_feature: 'str', fillet_name: 'str', radius: 'float', edge_refs: 'list[str] | None' = None, body_name: 'str | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.fillet_feature_operation",
            rpc_method="fillet_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_advanced_b",
        ),
        ToolEntry(
            name="helical_sweep_feature",
            docstring='Sweep a profile along a helix (PartDesign::AdditiveHelix).\n\nUse this to create springs, screw threads, worm gear blanks, etc.\n\nArgs:\n    doc_name: Document containing the sketch and body.\n    profile_sketch: Name of the cross-section sketch.\n    helix_name: Name for the resulting Helix feature.\n    pitch: Distance between successive turns in mm.\n    height: Total height of the helix in mm.\n    radius: Helix radius in mm.\n    body_name: Optional explicit PartDesign Body name.\n    left_handed: If true, produce a left-handed helix.\n    reversed_dir: If true, reverse the helix direction.\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', profile_sketch: 'str', helix_name: 'str', pitch: 'float', height: 'float', radius: 'float', body_name: 'str | None' = None, left_handed: 'bool' = False, reversed_dir: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.helical_sweep_feature_operation",
            rpc_method="helical_sweep_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_advanced_b",
        ),
        ToolEntry(
            name="linear_pattern_feature",
            docstring='Repeat an existing PartDesign feature along a straight direction.\n\nUse this after creating a sketch-based feature such as a Pad or Pocket.\nThe source feature must be inside a PartDesign Body.\n\nArgs:\n    doc_name: The document containing the body and source feature.\n    feature_name: Existing feature to repeat, for example `Pocket` or `Pad`.\n    pattern_name: Name for the resulting LinearPattern feature.\n    length: Total pattern length in mm.\n    occurrences: Number of repeated instances, including the original.\n    direction: Axis or reference edge. Examples: `X_Axis`, `Y_Axis`,\n        `Z_Axis`, or `ObjectName:Edge1`.\n    body_name: Optional explicit PartDesign Body name.\n    reversed_dir: If true, reverse the pattern direction.\n\nReturns:\n    A message indicating success or failure and an isometric screenshot.\n\nExamples:\n    Pattern a pocket 5 times over 40 mm along X:\n    ```json\n    {"doc_name": "Part", "feature_name": "Pocket", "pattern_name": "PocketArray",\n     "length": 40, "occurrences": 5}\n    ```',
            signature="(ctx: 'Context', doc_name: 'str', feature_name: 'str', pattern_name: 'str', length: 'float', occurrences: 'int', direction: 'str' = 'X_Axis', body_name: 'str | None' = None, reversed_dir: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.linear_pattern_feature_operation",
            rpc_method="linear_pattern_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_basic_1",
        ),
        ToolEntry(
            name="pad_feature",
            docstring='Extrude (pad) a closed sketch profile into a 3-D solid (PartDesign::Pad).\n\nStrict PartDesign: the Pad is always created inside a PartDesign Body. If\n`body_name` is given it must resolve; otherwise the Body that owns the sketch\nis auto-detected. If no owning Body can be found the tool FAILS -- it never\nfalls back to a loose, non-parametric feature in the document. Before building,\nthe sketch is checked for conflicting/malformed constraints and a closed\nprofile; after building, Body membership, Body.Tip, and a non-null solid are\nverified. The whole build is wrapped in a transaction, so a failed check leaves\nno partial feature behind.\n\nArgs:\n    doc_name: The document containing the sketch and body.\n    sketch_name: Name of the sketch to extrude.\n    pad_name: Name for the resulting Pad feature.\n    length: Extrusion distance in mm.\n    body_name: Optional explicit PartDesign Body name.\n    symmetric: If true, extrude equally in both directions (length/2 each).\n    reversed_dir: If true, reverse the extrusion direction.\n    strict: If true, require an explicit `body_name` (owning-Body auto-detect\n        is disabled). Recommended for a deterministic PartDesign history.\n\nReturns:\n    A structured JSON workflow result (document, body, sketch, feature,\n    attachment, tip, solid_count, state, bbox, diagnostics) plus an isometric\n    screenshot, or a clear failure.\n\nExamples:\n    Pad "Sketch" by 15 mm inside "Body":\n    ```json\n    {"doc_name": "Part", "sketch_name": "Sketch", "pad_name": "Pad", "length": 15,\n     "body_name": "Body"}\n    ```',
            signature="(ctx: 'Context', doc_name: 'str', sketch_name: 'str', pad_name: 'str', length: 'float', body_name: 'str | None' = None, symmetric: 'bool' = False, reversed_dir: 'bool' = False, strict: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.pad_feature_operation",
            rpc_method="pad_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_basic_1",
        ),
        ToolEntry(
            name="pocket_feature",
            docstring='Cut (pocket) a closed sketch profile into an existing solid (PartDesign::Pocket).\n\nStrict PartDesign: the Pocket is always created inside a PartDesign Body. If\n`body_name` is given it must resolve; otherwise the Body that owns the sketch\nis auto-detected. If no owning Body can be found the tool FAILS -- it never\nfalls back to a loose feature in the document. Before building, the sketch is\nchecked for conflicting/malformed constraints and a closed profile; after\nbuilding, Body membership, Body.Tip, and a non-null solid are verified. The\nwhole build is wrapped in a transaction, so a failed check leaves no partial\nfeature behind.\n\nArgs:\n    doc_name: The document containing the sketch and body.\n    sketch_name: Name of the sketch to use as the cut profile.\n    pocket_name: Name for the resulting Pocket feature.\n    length: Cut depth in mm.\n    body_name: Optional explicit PartDesign Body name.\n    symmetric: If true, cut equally in both directions.\n    reversed_dir: If true, reverse the cut direction.\n    strict: If true, require an explicit `body_name` (owning-Body auto-detect\n        is disabled). Recommended for a deterministic PartDesign history.\n\nReturns:\n    A structured JSON workflow result (document, body, sketch, feature,\n    attachment, tip, solid_count, state, bbox, diagnostics) plus an isometric\n    screenshot, or a clear failure.\n\nExamples:\n    Pocket "HoleSketch" by 5 mm:\n    ```json\n    {"doc_name": "Part", "sketch_name": "HoleSketch", "pocket_name": "Pocket",\n     "length": 5, "body_name": "Body"}\n    ```',
            signature="(ctx: 'Context', doc_name: 'str', sketch_name: 'str', pocket_name: 'str', length: 'float', body_name: 'str | None' = None, symmetric: 'bool' = False, reversed_dir: 'bool' = False, strict: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.pocket_feature_operation",
            rpc_method="pocket_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_basic_1",
        ),
        ToolEntry(
            name="mirror_feature",
            docstring='Mirror an existing PartDesign feature across a plane.\n\nUse this after creating a sketch-based feature such as a Pad or Pocket.\nThe source feature must be inside a PartDesign Body.\n\nArgs:\n    doc_name: The document containing the body and source feature.\n    feature_name: Existing feature to mirror, for example `Pocket` or `Pad`.\n    mirror_name: Name for the resulting Mirrored feature.\n    plane: Mirror plane. Examples: `YZ_Plane`, `XZ_Plane`, `XY_Plane`,\n        or `ObjectName:Face1`.\n    body_name: Optional explicit PartDesign Body name.\n\nReturns:\n    A message indicating success or failure and an isometric screenshot.\n\nExamples:\n    Mirror a pocket across the YZ plane:\n    ```json\n    {"doc_name": "Part", "feature_name": "Pocket", "mirror_name": "PocketMirror",\n     "plane": "YZ_Plane"}\n    ```',
            signature="(ctx: 'Context', doc_name: 'str', feature_name: 'str', mirror_name: 'str', plane: 'str' = 'YZ_Plane', body_name: 'str | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.mirror_feature_operation",
            rpc_method="mirror_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_basic_2",
        ),
        ToolEntry(
            name="polar_pattern_feature",
            docstring='Repeat an existing PartDesign feature around an axis.\n\nUse this for circular hole patterns or radial repeats of sketch-based Pads\nand Pockets. The source feature must be inside a PartDesign Body.\n\nArgs:\n    doc_name: The document containing the body and source feature.\n    feature_name: Existing feature to repeat, for example `Pocket` or `Pad`.\n    pattern_name: Name for the resulting PolarPattern feature.\n    occurrences: Number of repeated instances, including the original.\n    angle: Total angular span in degrees. Defaults to 360.\n    axis: Axis or reference edge. Examples: `Z_Axis`, `X_Axis`, or\n        `ObjectName:Edge1`.\n    body_name: Optional explicit PartDesign Body name.\n    reversed_dir: If true, reverse the angular direction.\n\nReturns:\n    A message indicating success or failure and an isometric screenshot.\n\nExamples:\n    Pattern a pocket 6 times around the Z axis:\n    ```json\n    {"doc_name": "Part", "feature_name": "Pocket", "pattern_name": "BoltCircle",\n     "occurrences": 6}\n    ```',
            signature="(ctx: 'Context', doc_name: 'str', feature_name: 'str', pattern_name: 'str', occurrences: 'int', angle: 'float' = 360.0, axis: 'str' = 'Z_Axis', body_name: 'str | None' = None, reversed_dir: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.polar_pattern_feature_operation",
            rpc_method="polar_pattern_feature",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_basic_2",
        ),
        ToolEntry(
            name="boolean_difference",
            docstring='Subtract shape2 from shape1 (Part::Cut).\n\nArgs:\n    doc_name: Document containing both shapes.\n    shape1: Name of the base shape.\n    shape2: Name of the tool shape to subtract.\n    result_name: Name for the resulting cut shape.\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', shape1: 'str', shape2: 'str', result_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.boolean_difference_operation",
            rpc_method="boolean_difference",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_boolean",
        ),
        ToolEntry(
            name="boolean_intersection",
            docstring='Compute the Boolean intersection (common) of two shapes (Part::Common).\n\nArgs:\n    doc_name: Document containing both shapes.\n    shape1: Name of the first shape.\n    shape2: Name of the second shape.\n    result_name: Name for the resulting common shape.\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', shape1: 'str', shape2: 'str', result_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.boolean_intersection_operation",
            rpc_method="boolean_intersection",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_boolean",
        ),
        ToolEntry(
            name="boolean_union",
            docstring='Compute the Boolean union (fuse) of two shapes (Part::Fuse).\n\nArgs:\n    doc_name: Document containing both shapes.\n    shape1: Name of the first shape object.\n    shape2: Name of the second shape object.\n    result_name: Name for the resulting fused shape.\n\nReturns:\n    Success message and an isometric screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', shape1: 'str', shape2: 'str', result_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.boolean_union_operation",
            rpc_method="boolean_union",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_features_boolean",
        ),
    ),
)
