"""JSON-RPC client connection to a FreeCAD add-on instance."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .._shared.protocol.body_create_contract import BodyName, DocumentName


class FreeCADConnection:
    """Authenticated JSON-RPC client for one FreeCAD add-on RPC endpoint."""

    if TYPE_CHECKING:

        def body_create(
            self, doc_name: DocumentName, body_name: BodyName
        ) -> object: ...
        def _invoke_mutation_v2(self, method: str, params: object, **kwargs: object) -> object: ...
        def spreadsheet_create(self, doc_name: str, sheet_name: str) -> object: ...
        def spreadsheet_set_cells(self, doc_name: str, sheet_name: str, cells: object) -> object: ...
        def spreadsheet_get_cells(self, doc_name: str, sheet_name: str, addresses: object) -> object: ...
        def spreadsheet_set_alias(self, doc_name: str, sheet_name: str, address: str, alias: str) -> object: ...
        def spreadsheet_list_aliases(self, doc_name: str, sheet_name: str) -> object: ...
        def set_expression(self, doc_name: str, object_name: str, prop_path: str, expression: str) -> object: ...
        def clear_expression(self, doc_name: str, object_name: str, prop_path: str) -> object: ...
        def create_part_container(self, doc_name: str, part_name: str, parent_container: str | None = None, if_exists: str = "error") -> object: ...
        def move_object(self, doc_name: str, obj_name: str, target_container: str, remove_from_old_parent: bool = True) -> object: ...
        def create_datum_plane(self, doc_name: str, plane_name: str, body_name: str, mode: str, source_ref: str | None = None, face_a: str | None = None, face_b: str | None = None, offset_along_normal: object = None, map_mode: str = "FlatFace", if_exists: str = "error") -> object: ...
        def create_subshape_binder(self, doc_name: str, binder_name: str, source_object: str, sub_elements: object = None, target_body: str | None = None, target_container: str | None = None, relative: bool = False, sync_placement: bool = True, if_exists: str = "error") -> object: ...
        def build_path_wire(self, doc_name: str, wire_name: str, segments: object, tolerance_mm: float = 0.5, container: str | None = None, if_exists: str = "error") -> object: ...
        def sweep_pipe(self, doc_name: str, path_wire: str, diameter_mm: float, solid_name: str, profile_mode: str = "frenet", color: object = None, container: str | None = None, if_exists: str = "error") -> object: ...
        def sketch_add_external_projection(self, doc_name: str, sketch_name: str, source_ref: str, projection_mode: str = "auto", defining: bool = False, allow_gui_geometry_loop: bool = False) -> object: ...
        def preview_attachment(self, doc_name: str, datum_name: str) -> object: ...
        def create_placement_binder(self, doc_name: str, owner_body: str, name: str, source: str, relative: bool = True, bind_mode: str = "Synchronized") -> object: ...
        def create_placement_datum(self, doc_name: str, owner_body: str, name: str, source: str, relative: bool = True, offset: object = None) -> object: ...
        def capture_state(self, doc_name: str, object_names: object = None) -> object: ...
        def relink_references(self, doc_name: str, from_obj: str, to_obj: str) -> object: ...
        def snapshot(self, doc_name: str) -> object: ...
        def restore(self, doc_name: str, snapshot_id: str | None = None) -> object: ...
        def run_fem_analysis(self, doc_name: str, analysis_name: str, timeout: int = 600) -> object: ...
        def validate_movement_follow(self, doc_name: str, source: str, dependents: object, translation: object, axis: object, angle_deg: float, restore: bool = True, tolerance: float = 1e-07) -> object: ...
