"""Capability manifest for core (bootstrapped)."""

# ruff: noqa: E501
from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="core",
    register_modules=('tools_core_document', 'tools_core_execute', 'tools_core_objects'),
    tools=(
        ToolEntry(
            name="create_document",
            docstring='Create a new document in FreeCAD.\n\nArgs:\n    name: The name of the document to create.\n\nReturns:\n    A message indicating the success or failure of the document creation.\n\nExamples:\n    If you want to create a document named "MyDocument", you can use the following data.\n    ```json\n    {\n        "name": "MyDocument"\n    }\n    ```',
            signature="(ctx: 'Context', name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.create_document_operation",
            rpc_method="create_document",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_core_document",
        ),
        ToolEntry(
            name="create_object",
            docstring='Create a new object in FreeCAD.\nObject type is starts with "Part::" or "Draft::" or "PartDesign::" or "Fem::".\n\nNOTE: For mechanical parts the default workflow is a parametric PartDesign feature\nhistory (body_create -> sketch_create/sketch_attach -> constraints ->\nget_sketch_diagnostics -> pad_feature/pocket_feature), not generic primitives. Use\nthis tool for reference/non-parametric geometry, imported assets, temporary validation\nsolids, or when a specific primitive is explicitly requested. See the\nasset_creation_strategy prompt.\n\nArgs:\n    doc_name: The name of the document to create the object in.\n    obj_type: The type of the object to create (e.g. \'Part::Box\', \'Part::Cylinder\',\n        \'Draft::Circle\', \'PartDesign::Body\', etc.).\n    obj_name: The name of the object to create.\n    obj_properties: The properties of the object to create.\n\nReturns:\n    A message indicating the success or failure of the object creation and a\n    screenshot of the object.\n\nExamples:\n    If you want to create a cylinder with a height of 30 and a radius of 10,\n    you can use the following data.\n    ``Placement.Rotation.Angle`` is in degrees.\n    ```json\n    {\n        "doc_name": "MyCylinder",\n        "obj_name": "Cylinder",\n        "obj_type": "Part::Cylinder",\n        "obj_properties": {\n            "Height": 30,\n            "Radius": 10,\n            "Placement": {\n                "Base": {\n                    "x": 10,\n                    "y": 10,\n                    "z": 0\n                },\n                "Rotation": {\n                    "Axis": {\n                        "x": 0,\n                        "y": 0,\n                        "z": 1\n                    },\n                    "Angle": 45\n                }\n            },\n            "ViewObject": {\n                "ShapeColor": [0.5, 0.5, 0.5, 1.0]\n            }\n        }\n    }\n    ```\n\n    If you want to create a circle with a radius of 10, you can use the following data.\n    ```json\n    {\n        "doc_name": "MyCircle",\n        "obj_name": "Circle",\n        "obj_type": "Draft::Circle",\n    }\n    ```\n\n    If you want to create a FEM analysis, you can use the following data.\n    ```json\n    {\n        "doc_name": "MyFEMAnalysis",\n        "obj_name": "FemAnalysis",\n        "obj_type": "Fem::AnalysisPython",\n    }\n    ```\n\n    If you want to create a FEM constraint, you can use the following data.\n    ```json\n    {\n        "doc_name": "MyFEMConstraint",\n        "obj_name": "FemConstraint",\n        "obj_type": "Fem::ConstraintFixed",\n        "analysis_name": "MyFEMAnalysis",\n        "obj_properties": {\n            "References": [\n                {\n                    "object_name": "MyObject",\n                    "face": "Face1"\n                }\n            ]\n        }\n    }\n    ```\n\n    If you want to create a FEM mechanical material, you can use the following data.\n    ```json\n    {\n        "doc_name": "MyFEMAnalysis",\n        "obj_name": "FemMechanicalMaterial",\n        "obj_type": "Fem::MaterialCommon",\n        "analysis_name": "MyFEMAnalysis",\n        "obj_properties": {\n            "Material": {\n                "Name": "MyMaterial",\n                "Density": "7900 kg/m^3",\n                "YoungModulus": "210 GPa",\n                "PoissonRatio": 0.3\n            }\n        }\n    }\n    ```\n\n    If you want to create a FEM mesh, you can use the following data.\n    The `Shape` property is required (legacy `Part` is also accepted).\n    On FreeCAD 1.x the size limits are `CharacteristicLengthMax/Min`;\n    the legacy `ElementSizeMax/Min` keys are also accepted.\n    ```json\n    {\n        "doc_name": "MyFEMMesh",\n        "obj_name": "FemMesh",\n        "obj_type": "Fem::FemMeshGmsh",\n        "analysis_name": "MyFEMAnalysis",\n        "obj_properties": {\n            "Shape": "MyObject",\n            "CharacteristicLengthMax": 10,\n            "CharacteristicLengthMin": 0.1\n        }\n    }\n    ```',
            signature="(ctx: 'Context', doc_name: 'str', obj_type: 'str', obj_name: 'str', analysis_name: 'str | None' = None, obj_properties: 'dict[str, Any] | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.create_object_operation",
            rpc_method="create_object",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_core_document",
        ),
        ToolEntry(
            name="execute_code",
            docstring='Execute arbitrary Python code in FreeCAD.\n\nCHOOSING A MODE — expensive geometry loops must not run on the GUI thread.\nAny iteration (for/while/comprehension) containing an expensive OCCT call\n(``distToShape``/``isInside``/``common``/``cut``/``fuse``/``section``/\n``removeSplitter``/``isValid``/``check``) MUST use ``read_only=true`` +\n``execution_mode="worker"``\n+ ``timeout_seconds``. Such loops are non-interruptible on the GUI thread and\nwill freeze FreeCAD (a timeout cannot stop them). They are blocked in ``gui``\nmode unless you pass ``allow_gui_geometry_loop=true``, which is reserved for a\ngenuine, bounded live-document mutation that cannot run against a worker\nsnapshot. ``isInside`` sampling loops are worker-only and cannot use that\noverride. Split large sweeps into small batches, and after a GUI timeout do not\nresubmit GUI work until a liveness check (e.g. ``get_worker_status``) passes.\n``read_only=true`` may temporarily rotate/recompute geometry in the worker\nsnapshot; it only forbids modifying the live GUI documents.\n\nArgs:\n    code: The Python code to execute.\n    document: Target document name for scoped recompute/error reporting.\n    recompute: ``none`` (default for inspection), ``target``, or ``all``.\n    recompute_documents: Explicit document list to recompute when recompute is ``target``.\n    affected_documents: Complete declared write scope for mutating code.\n    read_only: Run only against an immutable FreeCADCmd snapshot. This never\n        executes arbitrary code against a live GUI document in any lease mode.\n    restore_active_document: Restore the active document after execution.\n    activate_document: Activate ``document`` before running code.\n    capture_view: Include a viewport screenshot (default false).\n    execution_mode: Conservative ``auto`` (default), explicit ``gui``, or\n        isolated ``worker``. ``read_only=True`` always selects the worker,\n        even if ``gui`` is requested.\n    timeout_seconds: Hard worker timeout from 1 to 900 seconds.\n    link_policy: Worker snapshot policy for broken joint/link refs. ``strict``\n        fails the snapshot; ``warn`` continues and returns ``link_warnings``.\n        Only meaningful with ``execution_mode="worker"``.\n    allow_gui_geometry_loop: Last-resort opt-in to run an expensive-geometry\n        loop on the GUI thread (``execution_mode="gui"``, ``read_only=false``)\n        for a genuine, bounded live-document mutation. Default false; prefer\n        read-only worker mode for any analysis.\n\nReturns:\n    Execution output with structured session/recompute metadata, or an error with traceback.',
            signature='(ctx: \'Context\', code: \'str\', document: \'str | None\' = None, recompute: \'str\' = \'none\', recompute_documents: \'list[str] | None\' = None, affected_documents: \'list[str] | None\' = None, read_only: \'bool\' = False, restore_active_document: \'bool\' = True, activate_document: \'bool\' = False, capture_view: \'bool\' = False, execution_mode: "Literal[\'gui\', \'worker\', \'auto\']" = \'auto\', timeout_seconds: \'float | None\' = None, link_policy: "Literal[\'strict\', \'warn\']" = \'strict\', allow_gui_geometry_loop: \'bool\' = False) -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.execute_code_operation",
            rpc_method="execute_code",
            execution_mode=ExecutionMode.GENERATED_SCRIPT,
            gui_thread=True,
            mutation_class=MutationClass.EXECUTION,
            register_module="tools_core_execute",
        ),
        ToolEntry(
            name="execute_code_async",
            docstring="Deprecated legacy background execution; blocked in lease enforcement.\n\nThis compatibility tool is unavailable in ``enforce`` mode because it has\nno explicit document scope or GUI-thread lease revalidation. Use snapshot\nworker analysis for read-only work and typed leased mutations to apply a\nresult. In off/observe compatibility mode, use this ONLY for long-running\nbackground computations that do NOT touch the\nFreeCAD GUI or mutate the FreeCAD document tree directly.\n\nThis tool runs the submitted code in a background thread and returns\nimmediately. Because it does not run on FreeCAD's main GUI thread, the code\nmust NOT call FreeCADGui APIs, manipulate the active view or selection, create\nor edit document objects, change object properties, call doc.recompute(), or\nsave documents.\n\nFor code that touches FreeCAD documents, document objects, FreeCADGui, the\nactive view, selection, or document objects, use typed RPC tools. Public\n``execute_code(read_only=True)`` runs only in an isolated snapshot worker;\nlive mutating execution is a separately enabled compatibility path and is\ndisabled by default in lease enforcement mode.\n\nUse execute_code_async only for background-safe work such as long-running\npure OCCT geometry calculations (e.g. fuse/cut/loft on already-fetched shapes)\nor other CPU-bound computations that do not interact with the document or GUI.\n\nTypical usage pattern:\n1. Fetch shapes into local variables first (via execute_code on the GUI thread).\n2. Store intermediate results in a module-level Python variable (not in the\n   FreeCAD document) so execute_code can read them later.\n3. Run the heavy computation via execute_code_async.\n4. After the expected computation time has elapsed, apply results to the\n   document via execute_code (which runs on the GUI thread).\n\nArgs:\n    code: Background-safe Python code to execute.\n\nReturns:\n    A message confirming that background execution has started.",
            signature="(ctx: 'Context', code: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.execute_code_async_operation",
            rpc_method="execute_code_async",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=True,
            mutation_class=MutationClass.EXECUTION,
            register_module="tools_core_execute",
        ),
        ToolEntry(
            name="delete_object",
            docstring="Delete an object without silently orphaning its dependents (I5 / P6).\n\nFreeCAD's delete deliberately does not remove an object's dependents, leaving\nthem Invalid. To avoid silent orphans this tool:\n  * ``recursive=True`` -> remove dependents (leaves first) then the object;\n  * ``force=True``      -> remove only the object and report the orphans left;\n  * otherwise           -> refuse and list the dependents so the agent decides.\n\nArgs:\n    doc_name: The name of the document to delete the object from.\n    obj_name: The name of the object to delete.\n    recursive: If True, delete the object's dependents first (no orphans).\n    force: If True, delete only the object even if it has dependents (orphans\n        remain and are reported).\n\nReturns:\n    JSON ``{ok, object, deleted, refused, dependents|orphans_left, ...}``\n    plus a recompute log of any non-clean objects, and a screenshot.",
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str', recursive: 'bool' = False, force: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.delete_object_operation",
            rpc_method="delete_object",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_core_objects",
        ),
        ToolEntry(
            name="edit_object",
            docstring='Edit an object in FreeCAD.\nThis tool is used when the `create_object` tool cannot handle the object creation.\n\nArgs:\n    doc_name: The name of the document to edit the object in.\n    obj_name: The name of the object to edit.\n    obj_properties: The properties of the object to edit. Placement-typed\n        properties such as ``Placement`` and ``AttachmentOffset`` accept the\n        same dict form returned by ``get_object``. ``Rotation.Angle`` is in\n        **degrees** (FreeCAD\'s Python ``Rotation.Angle`` property is radians;\n        MCP converts on serialize/deserialize so get→edit round-trips)::\n\n            {"Base": {"x": 0, "y": 0, "z": 10},\n             "Rotation": {"Axis": {"x": 0, "y": 0, "z": 1}, "Angle": 90}}\n\nReturns:\n    A message indicating the success or failure of the object editing and a\n    screenshot of the object.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str', obj_properties: 'dict[str, Any]') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.edit_object_operation",
            rpc_method="edit_object",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_core_objects",
        ),
        ToolEntry(
            name="inspect_references",
            docstring="Inspect link/subelement properties without evaluating their owner shapes.\n\nThis is the recovery-safe alternative to ``get_object`` for a document that\ncontains stale ``EdgeNNN``, ``FaceNNN``, or ``VertexNNN`` references. It\nscans link properties such as ``Support``, ``AttachmentSupport``, and a\nsketch's ordered ``ExternalGeometry`` list. It never recomputes the document.\n\nArgs:\n    doc_name: Open FreeCAD document name.\n    object_names: Optional owner objects to inspect; omit to scan the document.\n    only_invalid: Return only properties containing invalid subelements.\n    validate: Resolve referenced subelements on their target shapes. Leave\n        false for circularly broken documents; validity is then reported as\n        unevaluated instead of reading ``Shape``.\n\nReturns:\n    Structured link properties, preserving target and subelement order.",
            signature="(ctx: 'Context', doc_name: 'str', object_names: 'list[str] | None' = None, only_invalid: 'bool' = False, validate: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.inspect_references_operation",
            rpc_method="inspect_references",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_core_objects",
        ),
        ToolEntry(
            name="repair_references",
            docstring='Atomically replace broken link/subelement properties without recomputing.\n\nUse this when stale external geometry prevents normal MCP write/evaluate\ncalls. Each repair replaces one complete link property. Keeping the same\nreference-list order preserves Sketcher external-geometry indices.\n\nExample ``repairs`` value::\n\n    [{\n      "object": "ServoEdgeBinder",\n      "property": "Support",\n      "references": [{\n        "document": "Model",\n        "object": "ServoBody",\n        "subelements": ["Edge42"]\n      }]\n    }]\n\nBatch every known broken property into one call. The batch is preflighted\nand applied in a FreeCAD transaction. Recompute defaults to false so all\ncircularly broken links can be repaired before dependent geometry evaluates.\nThis tool does not save the document.\n\nArgs:\n    doc_name: Open FreeCAD document containing the owner objects.\n    repairs: Complete replacement references for each owner property.\n    recompute: Recompute once after committing the entire batch.\n    validate: Confirm proposed subelements exist before writing. This reads\n        target shapes, so leave false for the circular-recovery path and\n        validate with an explicit recompute after the complete batch.\n\nReturns:\n    Applied properties, commit state, deferred/attempted recompute state,\n    and any invalid links remaining on the repaired owner objects.',
            signature="(ctx: 'Context', doc_name: 'str', repairs: 'list[dict[str, Any]]', recompute: 'bool' = False, validate: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.repair_references_operation",
            rpc_method="repair_references",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_core_objects",
        ),
    ),
)
