from __future__ import annotations

from collections.abc import Callable

from .verb_extractors import _none_doc, _options_document, _params0_doc
from .verb_kind import VerbKind

# Every public FreeCADRPC verb must appear here. Missing → treated as MUTATING.
VERB_CLASSIFICATION: dict[str, tuple[VerbKind, Callable[[tuple], str | None]]] = {
    # Lifecycle / control
    "ping": (VerbKind.LIFECYCLE, _none_doc),
    "handshake_v2": (VerbKind.LIFECYCLE, _none_doc),
    "invoke_v2": (VerbKind.LIFECYCLE, _none_doc),
    "invoke_v2_control": (VerbKind.LIFECYCLE, _none_doc),
    "lease_heartbeat_batch": (VerbKind.LIFECYCLE, _none_doc),
    "lease_reconcile": (VerbKind.LIFECYCLE, _none_doc),
    "get_request_status": (VerbKind.LIFECYCLE, _none_doc),
    "cancel_request": (VerbKind.LIFECYCLE, _none_doc),
    "claim_acquisition_result": (VerbKind.LIFECYCLE, _none_doc),
    "acknowledge_acquisition_claim": (VerbKind.LIFECYCLE, _none_doc),
    "get_instance_info": (VerbKind.LIFECYCLE, _none_doc),
    "check_rpc_sync": (VerbKind.LIFECYCLE, _none_doc),
    "get_worker_status": (VerbKind.LIFECYCLE, _none_doc),
    "cancel_worker_job": (VerbKind.LIFECYCLE, _none_doc),
    "shutdown_rpc_server": (VerbKind.LIFECYCLE, _none_doc),
    # Lock verbs themselves
    "acquire_document_lock": (VerbKind.LIFECYCLE, _none_doc),
    "adopt_dirty_document": (VerbKind.LIFECYCLE, _none_doc),
    "get_document_lock": (VerbKind.LIFECYCLE, _none_doc),
    "list_document_locks": (VerbKind.LIFECYCLE, _none_doc),
    "heartbeat_document_lock": (VerbKind.LIFECYCLE, _none_doc),
    "update_document_lock": (VerbKind.LIFECYCLE, _none_doc),
    "release_document_lock": (VerbKind.LIFECYCLE, _none_doc),
    "save_document": (VerbKind.LIFECYCLE, _none_doc),
    "save_document_as": (VerbKind.LIFECYCLE, _none_doc),
    "finalize_document_edit": (VerbKind.LIFECYCLE, _none_doc),
    "force_release_stale_lock": (VerbKind.LIFECYCLE, _none_doc),
    # Document open/create (create needs no prior lease; open is read of file)
    "create_document": (VerbKind.MUTATING, _none_doc),  # no prior doc; gated specially
    "open_document": (VerbKind.READ_ONLY, _none_doc),
    "list_documents": (VerbKind.READ_ONLY, _none_doc),
    "activate_document": (VerbKind.READ_ONLY, _params0_doc),
    "reload_document": (VerbKind.MUTATING, _params0_doc),
    "close_document": (VerbKind.MUTATING, _params0_doc),
    # Mutating model ops
    "create_object": (VerbKind.MUTATING, _params0_doc),
    "edit_object": (VerbKind.MUTATING, _params0_doc),
    "delete_object": (VerbKind.MUTATING, _params0_doc),
    "repair_references": (VerbKind.MUTATING, _params0_doc),
    "insert_part_from_library": (VerbKind.MUTATING, _params0_doc),
    "recompute_document": (VerbKind.MUTATING, _params0_doc),
    "recompute_and_wait": (VerbKind.MUTATING, _params0_doc),
    "undo": (VerbKind.MUTATING, _params0_doc),
    "redo": (VerbKind.MUTATING, _params0_doc),
    "restore": (VerbKind.MUTATING, _params0_doc),
    "snapshot": (VerbKind.READ_ONLY, _params0_doc),
    "run_fem_analysis": (VerbKind.MUTATING, _params0_doc),
    "solve_assembly": (VerbKind.MUTATING, _params0_doc),
    "sketch_create": (VerbKind.MUTATING, _params0_doc),
    "sketch_add_geometry": (VerbKind.MUTATING, _params0_doc),
    "sketch_add_constraint": (VerbKind.MUTATING, _params0_doc),
    "sketch_delete_constraint": (VerbKind.MUTATING, _params0_doc),
    "sketch_delete_geometry": (VerbKind.MUTATING, _params0_doc),
    "sketch_attach": (VerbKind.MUTATING, _params0_doc),
    "sketch_edit_constraint": (VerbKind.MUTATING, _params0_doc),
    "pad_feature": (VerbKind.MUTATING, _params0_doc),
    "pocket_feature": (VerbKind.MUTATING, _params0_doc),
    "spreadsheet_create": (VerbKind.MUTATING, _params0_doc),
    "spreadsheet_set_cells": (VerbKind.MUTATING, _params0_doc),
    "spreadsheet_set_alias": (VerbKind.MUTATING, _params0_doc),
    "set_expression": (VerbKind.MUTATING, _params0_doc),
    "clear_expression": (VerbKind.MUTATING, _params0_doc),
    "body_create": (VerbKind.MUTATING, _params0_doc),
    "body_set_tip": (VerbKind.MUTATING, _params0_doc),
    "animate_placement": (VerbKind.MUTATING, _params0_doc),
    "repair_view_placements": (VerbKind.MUTATING, _params0_doc),
    "execute_code": (VerbKind.MUTATING, _options_document),
    "execute_code_async": (VerbKind.MUTATING, _none_doc),
    # Read-only
    "inspect_references": (VerbKind.READ_ONLY, _params0_doc),
    "get_objects": (VerbKind.READ_ONLY, _params0_doc),
    "get_object": (VerbKind.READ_ONLY, _params0_doc),
    "get_parts_list": (VerbKind.READ_ONLY, _none_doc),
    "get_active_screenshot": (VerbKind.READ_ONLY, _none_doc),
    "capture_view_sequence": (VerbKind.READ_ONLY, _none_doc),
    "capture_view_sequence_to_disk": (VerbKind.READ_ONLY, _none_doc),
    "refresh_view": (VerbKind.READ_ONLY, _none_doc),
    "get_selection": (VerbKind.READ_ONLY, _none_doc),
    "get_gui_state": (VerbKind.READ_ONLY, _none_doc),
    "set_tree_expanded": (VerbKind.READ_ONLY, _params0_doc),
    "select_subshapes": (VerbKind.READ_ONLY, _params0_doc),
    "set_section_view": (VerbKind.READ_ONLY, _none_doc),
    "get_recompute_log": (VerbKind.READ_ONLY, _params0_doc),
    "spreadsheet_get_cells": (VerbKind.READ_ONLY, _params0_doc),
    "spreadsheet_list_aliases": (VerbKind.READ_ONLY, _params0_doc),
    "list_expressions": (VerbKind.READ_ONLY, _params0_doc),
    "diagnose_parametric": (VerbKind.READ_ONLY, _params0_doc),
    "get_sketch_diagnostics": (VerbKind.READ_ONLY, _params0_doc),
}
