"""Capability manifest for gui (bootstrapped)."""

# ruff: noqa: E501
from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="gui",
    register_modules=('tools_gui_document_a', 'tools_gui_document_b', 'tools_gui_view_a', 'tools_gui_view_b'),
    tools=(
        ToolEntry(
            name="get_object",
            docstring='Get an object from a document.\nYou can use this tool to get the properties of an object to see what you can check or edit.\n\nArgs:\n    doc_name: The name of the document to get the object from.\n    obj_name: The name of the object to get.\n\nReturns:\n    The object and a screenshot of the object.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_object_operation",
            rpc_method="get_object",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_document_a",
        ),
        ToolEntry(
            name="get_objects",
            docstring='Get all objects in a document.\nYou can use this tool to get the objects in a document to see what you can check or edit.\n\nArgs:\n    doc_name: The name of the document to get the objects from.\n\nReturns:\n    A list of objects in the document and a screenshot of the document.',
            signature="(ctx: 'Context', doc_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_objects_operation",
            rpc_method="get_objects",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_document_a",
        ),
        ToolEntry(
            name="get_parts_list",
            docstring='Get the list of parts in the parts library addon.',
            signature="(ctx: 'Context') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_parts_list_operation",
            rpc_method="get_parts_list",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_document_a",
        ),
        ToolEntry(
            name="insert_part_from_library",
            docstring='Insert a part from the parts library into an explicit leased document.\n\nArgs:\n    doc_name: Target FreeCAD document name.\n    relative_path: The relative path of the part to insert.\n\nReturns:\n    A message indicating the success or failure of the part insertion and a\n    screenshot of the object.',
            signature="(ctx: 'Context', doc_name: 'str', relative_path: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.insert_part_from_library_operation",
            rpc_method="insert_part_from_library",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_document_a",
        ),
        ToolEntry(
            name="list_documents",
            docstring='Get the list of open documents in FreeCAD.\n\nReturns:\n    A list of document names.',
            signature="(ctx: 'Context') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.list_documents_operation",
            rpc_method="list_documents",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_document_a",
        ),
        ToolEntry(
            name="open_document",
            docstring='Open a ``.FCStd`` (or other FreeCAD-supported) file in the running GUI.\n\nUse this to load V7 and V8 into the same FreeCAD session for comparison.',
            signature="(ctx: 'Context', path: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.open_document_operation",
            rpc_method="open_document",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_document_a",
        ),
        ToolEntry(
            name="reload_document",
            docstring='Close and re-open a document to pick up external file changes.\n\nUse this AFTER the document\'s .FCStd file has been modified by\nsomething outside of FreeCAD\'s GUI process — for example, a\nheadless `freecadcmd` script that edited and saved the file. The\nopen GUI document is otherwise unaware of on-disk changes; this\ntool closes the stale in-memory copy and reopens the file from\ndisk so the GUI shows current geometry.\n\nArgs:\n    doc_name: The name of the open document to reload. Must match\n        the name shown by ``list_documents``.\n\nReturns:\n    A message confirming the document was reloaded, or describing\n    the failure (document not loaded, no associated file, etc).\n\nExamples:\n    ```json\n    {\n        "doc_name": "chassis"\n    }\n    ```',
            signature="(ctx: 'Context', doc_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.reload_document_operation",
            rpc_method="reload_document",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_document_a",
        ),
        ToolEntry(
            name="activate_document",
            docstring='Make an already-open document the active GUI document.',
            signature="(ctx: 'Context', doc_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.activate_document_operation",
            rpc_method="activate_document",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_document_b",
        ),
        ToolEntry(
            name="get_gui_state",
            docstring='Report the active GUI context (read-only).\n\nReturns JSON with the active document, active PartDesign Body, active\nworkbench, the object currently in edit-mode, and the current selection.\nUse it to orient before editing -- e.g. confirm the right Body is active\nbefore adding a sketch/feature, or check whether a Sketch is open for edit.',
            signature="(ctx: 'Context') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_gui_state_operation",
            rpc_method="get_gui_state",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_document_b",
        ),
        ToolEntry(
            name="get_selection",
            docstring='Return the current FreeCADGui selection (document/object/sub).',
            signature="(ctx: 'Context') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_selection_operation",
            rpc_method="get_selection",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_document_b",
        ),
        ToolEntry(
            name="recompute_and_wait",
            docstring='Recompute a document and block until the GUI is idle, then report state.\n\nAn explicit recompute-complete + GUI-idle barrier: runs the recompute on the\nGUI thread, drains queued Qt events, and returns per-object recompute state\n(errors, still-Touched objects, whether the document settled). Run it after a\nbatch of edits, or after an execute_code that may have left async work, before\ntrusting follow-up model checks. Complements ``check_rpc_sync`` (which only\nproves the RPC queue is live, not that a recompute finished).',
            signature="(ctx: 'Context', doc_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.recompute_and_wait_operation",
            rpc_method="recompute_and_wait",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=True,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_document_b",
        ),
        ToolEntry(
            name="select_subshapes",
            docstring='Select GUI-visible objects or sub-shapes (FaceN/EdgeN/VertexN).\n\nEach selection may be ``"Box"``, ``"Box:Face1"``, or\n``{"object": "Box", "sub": "Face1"}``. Prefer ``find_faces`` to\ndiscover indices, then this tool to highlight them in the GUI.',
            signature="(ctx: 'Context', doc_name: 'str', selections: 'list[Any]', clear: 'bool' = True) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.select_subshapes_operation",
            rpc_method="select_subshapes",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_document_b",
        ),
        ToolEntry(
            name="set_section_view",
            docstring='Enable, disable, or query the active view clipping (section) plane.\n\nPass ``enabled=True/False`` to toggle. Optionally set plane ``base`` +\n``normal`` (or a full ``placement`` dict). Omit args to query status.',
            signature="(ctx: 'Context', enabled: 'bool | None' = None, base: 'list[float] | None' = None, normal: 'list[float] | None' = None, placement: 'dict[str, Any] | None' = None, no_manip: 'bool' = True) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.set_section_view_operation",
            rpc_method="set_section_view",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_document_b",
        ),
        ToolEntry(
            name="set_tree_expanded",
            docstring='Expand or collapse model-tree items in the FreeCAD GUI.\n\nSelects ``object_names`` then runs Std_TreeExpand / Std_TreeCollapse.\nModes ``expand_document`` / ``collapse_document`` operate on the whole tree.',
            signature='(ctx: \'Context\', doc_name: \'str\', object_names: \'list[str] | None\' = None, mode: "Literal[\'expand\', \'collapse\', \'expand_document\', \'collapse_document\']" = \'expand\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.set_tree_expanded_operation",
            rpc_method="set_tree_expanded",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_document_b",
        ),
        ToolEntry(
            name="encode_view_video",
            docstring='Encode a view sequence to MP4 using system ffmpeg (not a git submodule).\n\nProvide existing ``frame_paths`` and/or capture via ``frames``/``orbit``\n(same shape as ``save_view_sequence``). Resolves ffmpeg from\n``FREECAD_MCP_FFMPEG`` or PATH.',
            signature="(ctx: 'Context', frames: 'list[dict[str, Any]] | None' = None, orbit: 'dict[str, Any] | None' = None, frame_paths: 'list[str] | None' = None, output_path: 'str | None' = None, fps: 'float' = 8.0, width: 'int | None' = None, height: 'int | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.encode_view_video_operation",
            rpc_method="encode_view_video",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_view_a",
        ),
        ToolEntry(
            name="get_view",
            docstring='Get a screenshot of the active view.\n\nArgs:\n    view_name: Standard view preset. Aliases: Rear→Back, Side/SideRight→Right, SideLeft→Left.\n    Available: Isometric, Front, Top, Right, Back, Left, Bottom, Dimetric, Trimetric\n    (plus Rear, Side, SideRight, SideLeft aliases).\n    width: The width of the screenshot in pixels. If not specified, uses the viewport width.\n    height: The height of the screenshot in pixels. If not specified, uses the viewport height.\n    focus_object: Optional single object name to frame. Comma-separated names are\n        also accepted.\n    focus_objects: Optional list of object names to frame together (preferred for\n        stations/assemblies).\n    yaw_deg: Optional extra camera yaw in degrees after framing.\n\nReturns:\n    A screenshot of the active view.',
            signature='(ctx: \'Context\', view_name: "Literal[\'Isometric\', \'Front\', \'Top\', \'Right\', \'Back\', \'Left\', \'Bottom\', \'Dimetric\', \'Trimetric\', \'Rear\', \'Side\', \'SideRight\', \'SideLeft\']", width: \'int | None\' = None, height: \'int | None\' = None, focus_object: \'str | None\' = None, focus_objects: \'list[str] | None\' = None, yaw_deg: \'float | None\' = None) -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.get_view_operation",
            rpc_method="get_view",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_view_a",
        ),
        ToolEntry(
            name="save_view_sequence",
            docstring='Capture multiple framed screenshots for motion/station review.\n\nProvide ``frames`` and/or ``orbit``.\n\nFrame dict fields:\n- ``view_name`` (default ``Isometric``)\n- ``focus_object`` / ``focus_objects``\n- ``yaw_deg``\n- ``label``\n\nOrbit dict fields:\n- ``focus_object`` / ``focus_objects``\n- ``steps`` (default 8)\n- ``view_name`` (default ``Isometric``)\n- ``yaw_start_deg`` (default 0)\n\nReturns text metadata plus one PNG image per successful frame.',
            signature="(ctx: 'Context', frames: 'list[dict[str, Any]] | None' = None, width: 'int | None' = None, height: 'int | None' = None, orbit: 'dict[str, Any] | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.save_view_sequence_operation",
            rpc_method="save_view_sequence",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_gui_view_a",
        ),
        ToolEntry(
            name="animate_placement",
            docstring="Animate an object's Placement along keyframes or a path wire, capture frames, restore.\n\nPrefer this over Shape edits for App::Link visibility. Optionally encodes MP4\nvia system ffmpeg when ``encode_video=True``.",
            signature='(ctx: \'Context\', doc_name: \'str\', obj_name: \'str\', keyframes: \'list[dict[str, Any]] | None\' = None, path_object: \'str | None\' = None, sample_count: \'int\' = 12, view_name: "Literal[\'Isometric\', \'Front\', \'Top\', \'Right\', \'Back\', \'Left\', \'Bottom\', \'Dimetric\', \'Trimetric\']" = \'Isometric\', focus_objects: \'list[str] | None\' = None, width: \'int | None\' = None, height: \'int | None\' = None, encode_video: \'bool\' = False, fps: \'float\' = 8.0, output_path: \'str | None\' = None) -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.animate_placement_operation",
            rpc_method="animate_placement",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_view_b",
        ),
        ToolEntry(
            name="refresh_view",
            docstring='Force a GUI redraw after Link/shape edits; optionally touch Placement and frame.',
            signature='(ctx: \'Context\', focus_objects: \'list[str] | None\' = None, focus_object: \'str | None\' = None, touch_objects: \'list[str] | None\' = None, fit: \'bool\' = False, capture: \'bool\' = False, view_name: "Literal[\'Isometric\', \'Front\', \'Top\', \'Right\', \'Back\', \'Left\', \'Bottom\', \'Dimetric\', \'Trimetric\']" = \'Isometric\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.operations.refresh_view_operation",
            rpc_method="refresh_view",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_view_b",
        ),
        ToolEntry(
            name="repair_view_placements",
            docstring="Reassign selected Placement values under the document's active lease.",
            signature="(ctx: 'Context', doc_name: 'str', touch_objects: 'list[str]', fit: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.repair_view_placements_operation",
            rpc_method="repair_view_placements",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_gui_view_b",
        ),
    ),
)
