"""Phase 0 surface regressions for integrator-owned seams."""

from __future__ import annotations

import pytest

from freecad_mcp.outcomes import LayerStatus, OutcomeStatus

pytestmark = pytest.mark.unit


@pytest.mark.parametrize(
    ("status", "wire_value"),
    [
        (OutcomeStatus.SUCCEEDED, "succeeded"),
        (OutcomeStatus.CONDITION_FALSE, "condition_false"),
        (OutcomeStatus.WARNING, "warning"),
        (OutcomeStatus.DEGRADED, "degraded"),
        (OutcomeStatus.REJECTED, "rejected"),
        (OutcomeStatus.FAILED, "failed"),
        (OutcomeStatus.TIMED_OUT, "timed_out"),
        (OutcomeStatus.CANCELLED, "cancelled"),
        (OutcomeStatus.UNKNOWN, "unknown"),
    ],
)
def test_outcome_status_strenum_wire_values(status: OutcomeStatus, wire_value: str) -> None:
    assert str(status) == wire_value
    assert status.value == wire_value


@pytest.mark.parametrize(
    ("status", "wire_value"),
    [
        (LayerStatus.SUCCEEDED, "succeeded"),
        (LayerStatus.CONDITION_FALSE, "condition_false"),
        (LayerStatus.WARNING, "warning"),
        (LayerStatus.DEGRADED, "degraded"),
        (LayerStatus.REJECTED, "rejected"),
        (LayerStatus.FAILED, "failed"),
        (LayerStatus.TIMED_OUT, "timed_out"),
        (LayerStatus.CANCELLED, "cancelled"),
        (LayerStatus.NOT_APPLICABLE, "not_applicable"),
        (LayerStatus.UNKNOWN, "unknown"),
    ],
)
def test_layer_status_strenum_wire_values(status: LayerStatus, wire_value: str) -> None:
    assert str(status) == wire_value
    assert status.value == wire_value


# HEAD baseline membership for src/freecad_mcp/operations/__init__.py::__all__
EXPECTED_OPERATIONS_ALL = frozenset(
    {
        "acquire_document_lock_operation",
        "activate_document_operation",
        "adopt_dirty_document_operation",
        "animate_placement_operation",
        "audit_hardcoded_dimensions_operation",
        "body_create_operation",
        "body_set_tip_operation",
        "boolean_difference_operation",
        "boolean_intersection_operation",
        "boolean_union_operation",
        "bounding_box_operation",
        "build_path_wire_operation",
        "capture_state_operation",
        "center_of_mass_operation",
        "chamfer_feature_operation",
        "check_gear_pair_operation",
        "claim_acquisition_result_operation",
        "clear_expression_operation",
        "close_document_operation",
        "common_volume_along_path_operation",
        "compare_documents_operation",
        "compute_gear_geometry_operation",
        "create_assembly_grounded_joint_operation",
        "create_assembly_joint_operation",
        "create_assembly_operation",
        "create_datum_plane_operation",
        "create_document_operation",
        "create_helical_gear_operation",
        "create_involute_gear_operation",
        "create_object_operation",
        "create_part_container_operation",
        "create_placement_binder_operation",
        "create_placement_datum_operation",
        "create_spur_gear_operation",
        "create_subshape_binder_operation",
        "delete_object_operation",
        "diagnose_helix_operation",
        "diagnose_parametric_operation",
        "diagnose_pocket_operation",
        "edge_axis_operation",
        "edit_object_operation",
        "encode_view_video_operation",
        "execute_code_async_operation",
        "execute_code_operation",
        "export_brep_operation",
        "export_step_operation",
        "export_stl_operation",
        "face_normal_operation",
        "fillet_feature_operation",
        "find_edges_operation",
        "find_faces_operation",
        "force_release_stale_lock_operation",
        "forget_legacy_document_key",
        "geometric_diff_operation",
        "get_dependency_graph_operation",
        "get_document_lock_operation",
        "get_document_tree_operation",
        "get_global_shape_operation",
        "get_gui_state_operation",
        "get_object_operation",
        "get_objects_operation",
        "get_parts_list_operation",
        "get_recompute_log_operation",
        "get_mutation_readiness_operation",
        "get_report_view_operation",
        "get_selection_operation",
        "get_sketch_diagnostics_operation",
        "get_sketch_geometry_operation",
        "get_view_operation",
        "heartbeat_document_lock_operation",
        "helical_sweep_feature_operation",
        "import_brep_operation",
        "import_step_operation",
        "insert_part_from_library_operation",
        "inspect_geometry_operation",
        "inspect_references_operation",
        "legacy_selector_doc_key",
        "linear_pattern_feature_operation",
        "list_document_locks_operation",
        "list_documents_operation",
        "list_expressions_operation",
        "loft_feature_operation",
        "match_subshape_operation",
        "measure_angle_operation",
        "measure_area_operation",
        "measure_distance_operation",
        "measure_volume_operation",
        "mirror_feature_operation",
        "move_object_operation",
        "open_document_operation",
        "pad_feature_operation",
        "placement_audit_operation",
        "pocket_feature_operation",
        "polar_pattern_feature_operation",
        "preview_attachment_operation",
        "recompute_and_wait_operation",
        "recompute_document_operation",
        "redo_operation",
        "refresh_view_operation",
        "release_document_lock_operation",
        "relink_references_operation",
        "reload_document_operation",
        "repair_references_operation",
        "repair_view_placements_operation",
        "restore_operation",
        "revolve_feature_operation",
        "rotate_operation",
        "run_fem_analysis_operation",
        "run_transaction_operation",
        "save_view_sequence_operation",
        "scale_operation",
        "select_subshapes_operation",
        "set_color_operation",
        "set_expression_operation",
        "set_section_view_operation",
        "set_tree_expanded_operation",
        "sketch_add_arc_of_ellipse_operation",
        "sketch_add_arc_operation",
        "sketch_add_bezier_operation",
        "sketch_add_bspline_operation",
        "sketch_add_bspline_through_points_operation",
        "sketch_add_circle_operation",
        "sketch_add_constraint_operation",
        "sketch_add_ellipse_operation",
        "sketch_add_external_projection_operation",
        "sketch_add_geometry_operation",
        "sketch_add_line_operation",
        "sketch_add_parametric_curve_operation",
        "sketch_add_polyline_operation",
        "sketch_add_rectangle_operation",
        "sketch_add_regular_polygon_operation",
        "sketch_add_slot_operation",
        "sketch_attach_operation",
        "sketch_constrain_coincident_operation",
        "sketch_constrain_distance_operation",
        "sketch_constrain_equal_operation",
        "sketch_constrain_horizontal_operation",
        "sketch_constrain_parallel_operation",
        "sketch_constrain_perpendicular_operation",
        "sketch_constrain_radius_operation",
        "sketch_constrain_tangent_operation",
        "sketch_constrain_vertical_operation",
        "sketch_create_operation",
        "sketch_delete_constraint_operation",
        "sketch_delete_geometry_operation",
        "sketch_edit_constraint_operation",
        "sketch_extend_operation",
        "sketch_fillet_operation",
        "sketch_import_points_operation",
        "sketch_offset_operation",
        "sketch_split_operation",
        "sketch_symmetry_operation",
        "sketch_toggle_construction_operation",
        "sketch_trim_operation",
        "snapshot_operation",
        "spreadsheet_create_operation",
        "spreadsheet_get_cells_operation",
        "spreadsheet_list_aliases_operation",
        "spreadsheet_set_alias_operation",
        "spreadsheet_set_cells_operation",
        "sweep_feature_operation",
        "sweep_pipe_operation",
        "translate_operation",
        "undo_operation",
        "update_document_lock_operation",
        "validate_geometry_operation",
        "validate_movement_follow_operation",
    }
)


def test_operations_all_phase0_surface_is_167_symbols() -> None:
    import freecad_mcp.operations as ops

    assert frozenset(ops.__all__) == EXPECTED_OPERATIONS_ALL
    assert len(ops.__all__) == 167
    assert "solve_assembly_operation" not in ops.__all__
    # Import remains available for server.py and direct callers (I9).
    assert hasattr(ops, "solve_assembly_operation")
