"""Phase 22: hand-written capability mirror deletion and shim coverage."""

from __future__ import annotations

import importlib
import re
from pathlib import Path

import pytest

from freecad_mcp.capabilities.bootstrap import load_frozen_registry_snapshot
from freecad_mcp.capabilities.generator import (
    _bindings_from_source,
    connection_method_module_names,
    current_relocated_body_digests,
    load_relocated_body_digests,
    render_connection_method,
    render_connection_method_shim,
    render_connection_methods_package_init,
    render_production_client_stubs,
    render_register_module,
    render_register_module_shim,
    shadow_output_root,
    relocated_connection_method_body,
)
from freecad_mcp.capabilities.introspection import import_operation_symbol
from freecad_mcp.capabilities.load import all_subject_manifests
from freecad_mcp.generated.capabilities.register_order import REGISTER_TOOL_MODULES
from freecad_mcp.tools_register_order import REGISTER_TOOL_MODULES as SHIM_MODULES

pytestmark = pytest.mark.unit

_SPLIT_SUFFIX = re.compile(r"_(?:[ab]2?|[12])$")

# Frozen W2 subject ownership map for coordinator parallelization (Phase 22).
# Integrator owns generator, registration_runtime, and landing; workers are
# deferred until mirror→shim conversion can shard by subject without §5.3 races.
SUBJECT_MIRROR_MODULES: dict[str, tuple[str, ...]] = {
    "runtime": ("tools_runtime_info", "tools_runtime_control"),
    "lease": (
        "tools_lease_acquire_a",
        "tools_lease_acquire_b",
        "tools_lease_lifecycle",
    ),
    "core": ("tools_core_document", "tools_core_objects", "tools_core_execute"),
    "worker": ("tools_worker",),
    "gui": (
        "tools_gui_view_a",
        "tools_gui_view_b",
        "tools_gui_document_a",
        "tools_gui_document_b",
    ),
    "diagnostics": ("tools_diagnostics",),
    "sketch": (
        "tools_sketch_create_1",
        "tools_sketch_create_2",
        "tools_sketch_primitives",
        "tools_sketch_constraints_1",
        "tools_sketch_constraints_2",
        "tools_sketch_curves_a",
        "tools_sketch_curves_a2",
        "tools_sketch_curves_b",
        "tools_sketch_curves_b2",
    ),
    "features": (
        "tools_features_basic_1",
        "tools_features_basic_2",
        "tools_features_advanced_a",
        "tools_features_advanced_b",
        "tools_features_boolean",
    ),
    "document_history": ("tools_document_history",),
    "parametric": (
        "tools_parametric_sheet_a",
        "tools_parametric_sheet_b",
        "tools_parametric_body",
    ),
    "gear": ("tools_gear_1", "tools_gear_2"),
    "measure": ("tools_measure_a", "tools_measure_b"),
    "transform": ("tools_transform",),
    "io": ("tools_io_export", "tools_io_import"),
    "assembly": ("tools_assembly",),
    "partdesign": (
        "tools_partdesign_a",
        "tools_partdesign_a2",
        "tools_partdesign_b",
        "tools_partdesign_b2",
    ),
    "advanced": ("tools_advanced_a", "tools_advanced_b", "tools_advanced_b2"),
}


def _split_mirror_modules() -> tuple[str, ...]:
    return tuple(name for name in REGISTER_TOOL_MODULES if _SPLIT_SUFFIX.search(name))


def test_register_order_lists_forty_seven_modules():
    assert len(REGISTER_TOOL_MODULES) == 47
    assert list(SHIM_MODULES) == list(REGISTER_TOOL_MODULES)


def test_mechanical_split_mirror_count_is_thirty_one():
    assert len(_split_mirror_modules()) == 31


def test_subject_mirror_map_covers_every_register_module():
    mapped = {name for names in SUBJECT_MIRROR_MODULES.values() for name in names}
    assert mapped == set(REGISTER_TOOL_MODULES)


@pytest.mark.parametrize("module_name", REGISTER_TOOL_MODULES)
def test_legacy_register_module_import_paths_remain_importable(module_name: str):
    module = importlib.import_module(f"freecad_mcp.{module_name}")
    assert callable(module.register)


def test_manifest_register_modules_match_register_order():
    manifest_modules = {
        module_name
        for manifest in all_subject_manifests()
        for module_name in manifest.register_modules
    }
    assert manifest_modules == set(REGISTER_TOOL_MODULES)


def test_relocated_register_module_bodies_match_frozen_digests():
    snapshot = load_frozen_registry_snapshot()
    frozen = load_relocated_body_digests()
    current = current_relocated_body_digests(
        register_modules=tuple(snapshot["register_order"])
    )
    assert current["register_modules"] == frozen["register_modules"]


def test_render_register_module_rewrites_relative_imports():
    source = (
        "from ..operations import sketch_create_operation\n\n"
        "def register() -> None:\n"
        "  del sketch_create_operation\n"
    )
    rendered = render_register_module("tools_sample", source)
    assert "from freecad_mcp.operations import sketch_create_operation" in rendered
    assert rendered.startswith('"""GENERATED by freecad_mcp.capabilities.generator')


@pytest.mark.parametrize("module_name", REGISTER_TOOL_MODULES)
def test_register_module_shims_reexport_generated_register(module_name: str):
    shim = importlib.import_module(f"freecad_mcp.{module_name}")
    generated = importlib.import_module(
        f"freecad_mcp.generated.capabilities.register_modules.{module_name}"
    )
    assert shim.register is generated.register


def test_split_mirror_modules_are_declarative_shims():
    for module_name in _split_mirror_modules():
        text = (
            Path(__file__).resolve().parents[1]
            / "src"
            / "freecad_mcp"
            / f"{module_name}.py"
        ).read_text(encoding="utf-8")
        assert text == render_register_module_shim(module_name)


def test_inline_runtime_info_operation_path_is_importable():
    symbol = import_operation_symbol(
        "freecad_mcp.capabilities.inline.tools_runtime_info.get_runtime_info"
    )
    assert callable(symbol)


def test_connection_method_module_count_is_twenty_two():
    assert len(connection_method_module_names()) == 22


@pytest.mark.parametrize("module_name", connection_method_module_names())
def test_connection_method_shims_reexport_generated_symbols(module_name: str):
    shim = importlib.import_module(
        f"freecad_mcp.freecad_client_ops.connection_methods.{module_name}"
    )
    generated = importlib.import_module(
        f"freecad_mcp.generated.capabilities.connection_methods.{module_name}"
    )
    expected = _bindings_from_source(relocated_connection_method_body(module_name))
    assert tuple(shim.__all__) == expected
    for name in shim.__all__:
        assert getattr(shim, name) is getattr(generated, name)


def test_connection_methods_package_reexports_public_symbols():
    package = importlib.import_module("freecad_mcp.freecad_client_ops.connection_methods")
    assert callable(package.ping)
    assert callable(package.create_document)
    assert package.ping is importlib.import_module(
        "freecad_mcp.generated.capabilities.connection_methods.connection_read_ops"
    ).ping


def test_connection_methods_package_private_symbol_via_submodule():
    helpers = importlib.import_module(
        "freecad_mcp.freecad_client_ops.connection_methods.connection_v2_context_helpers"
    )
    generated = importlib.import_module(
        "freecad_mcp.generated.capabilities.connection_methods.connection_v2_context_helpers"
    )
    assert helpers.resolve_document_name_sessions is generated.resolve_document_name_sessions


def test_connection_method_modules_are_declarative_shims():
    methods_dir = (
        Path(__file__).resolve().parents[1]
        / "src"
        / "freecad_mcp"
        / "freecad_client_ops"
        / "connection_methods"
    )
    for module_name in connection_method_module_names():
        text = (methods_dir / f"{module_name}.py").read_text(encoding="utf-8")
        assert text == render_connection_method_shim(module_name)


def test_connection_methods_package_init_matches_emitter_output():
    methods_dir = (
        Path(__file__).resolve().parents[1]
        / "src"
        / "freecad_mcp"
        / "freecad_client_ops"
        / "connection_methods"
        / "__init__.py"
    )
    assert methods_dir.read_text(encoding="utf-8") == render_connection_methods_package_init()


def test_relocated_connection_method_bodies_match_frozen_digests():
    frozen = load_relocated_body_digests()
    current = current_relocated_body_digests()
    assert current["connection_methods"] == frozen["connection_methods"]


def test_render_connection_method_rewrites_parent_imports():
    source = (
        "from ..rpc_invocation_error import RpcInvocationError\n\n"
        "def ping(conn) -> bool:\n"
        "    return True\n"
    )
    rendered = render_connection_method("connection_read_ops", source)
    assert (
        "from freecad_mcp.freecad_client_ops.rpc_invocation_error import RpcInvocationError"
        in rendered
    )


def test_production_client_stubs_match_emitter_output():
    manifests = all_subject_manifests()
    actual = (shadow_output_root() / "client_stubs.py").read_text(encoding="utf-8")
    expected = render_production_client_stubs(manifests)
    assert actual == expected


def test_production_and_shadow_gateway_dispatch_are_byte_equal():
    root = shadow_output_root()
    production = (root / "gateway_dispatch.json").read_bytes()
    shadow = (root / "shadow_gateway_dispatch.json").read_bytes()
    assert production == shadow


def test_addon_gateway_dispatch_matches_production():
    addon_path = (
        Path(__file__).resolve().parents[1]
        / "addon"
        / "FreeCADMCP"
        / "generated"
        / "capabilities"
        / "gateway_dispatch.json"
    )
    production = (shadow_output_root() / "gateway_dispatch.json").read_bytes()
    assert addon_path.read_bytes() == production
