"""Capability manifest for advanced (bootstrapped)."""

# ruff: noqa: E501
from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="advanced",
    register_modules=('tools_advanced_a', 'tools_advanced_b', 'tools_advanced_b2'),
    tools=(
        ToolEntry(
            name="audit_hardcoded_dimensions",
            docstring='Report driving dimensions in a body that lack expressions (M8).',
            signature="(ctx: 'Context', doc_name: 'str', body_name: 'str', flag_aliases: 'bool' = True) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.audit_hardcoded_dimensions_operation",
            rpc_method="audit_hardcoded_dimensions",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_advanced_a",
        ),
        ToolEntry(
            name="get_dependency_graph",
            docstring='Property-annotated dependency graph from a root object (M13).',
            signature="(ctx: 'Context', doc_name: 'str', root: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_dependency_graph_operation",
            rpc_method="get_dependency_graph",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_advanced_a",
        ),
        ToolEntry(
            name="inspect_geometry",
            docstring='Normalized local/global geometry inspection for any object type (M10/M11).',
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str', subshape: 'str | None' = None, activate: 'bool' = False, restore_active_document: 'bool' = True) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.inspect_geometry_operation",
            rpc_method="inspect_geometry",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_advanced_a",
        ),
        ToolEntry(
            name="match_subshape",
            docstring='Rank target subshapes by semantic similarity to a source subshape (M14).',
            signature="(ctx: 'Context', doc_name: 'str', source_object: 'str', source_subshape: 'str', target_object: 'str', limit: 'int' = 10, tolerance: 'float' = 1.0) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.match_subshape_operation",
            rpc_method="match_subshape",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_advanced_a",
        ),
        ToolEntry(
            name="run_transaction",
            docstring="Retired transaction-code helper.\n\nGenerated callbacks cannot own transaction or history control inside FreeCAD's\nnative mutation coordinator. This tool always returns\n``RUN_TRANSACTION_RETIRED``; use typed modelling tools instead.",
            signature="(ctx: 'Context', doc_name: 'str', label: 'str', code: 'str', dry_run: 'bool' = False, commit_on_success: 'bool' = True) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.run_transaction_operation",
            rpc_method="run_transaction",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.EXECUTION,
            register_module="tools_advanced_a",
        ),
        ToolEntry(
            name="validate_movement_follow",
            docstring='Validate that dependents follow a source body under an arbitrary rigid transform (M7).',
            signature="(ctx: 'Context', doc_name: 'str', source: 'str', dependents: 'list[str]', translation: 'list[float]', axis: 'list[float]', angle_deg: 'float', restore: 'bool' = True, tolerance: 'float' = 1e-07) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.validate_movement_follow_operation",
            rpc_method="validate_movement_follow",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_advanced_a",
        ),
        ToolEntry(
            name="capture_state",
            docstring="Capture a compact geometric state for a set of objects (I10 / P10).\n\nRecords each object's placement, bounding box and face/edge counts. Pass the\nreturned JSON to ``geometric_diff`` to produce a text-only diff when a\nviewable image can't be returned.\n\nArgs:\n    doc_name: The document to capture.\n    object_names: Optional list of object names; all objects when None.",
            signature="(ctx: 'Context', doc_name: 'str', object_names: 'list[str] | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.capture_state_operation",
            rpc_method="capture_state",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_advanced_b",
        ),
        ToolEntry(
            name="geometric_diff",
            docstring="Structured geometric diff between a captured ``before`` state and now (I10).\n\nThe P10 text-only fallback: returns JSON\n``{ok, doc, diffs: [{name, bbox_before/after, placement_before/after,\nfaces_added/removed, changed}]}`` when a viewable image can't be returned.\n\nArgs:\n    doc_name: The document to diff against.\n    before: A state dict previously returned by ``capture_state``.\n    object_names: Optional list of object names; all objects when None.",
            signature="(ctx: 'Context', doc_name: 'str', before: 'dict', object_names: 'list[str] | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.geometric_diff_operation",
            rpc_method="geometric_diff",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_advanced_b",
        ),
        ToolEntry(
            name="relink_references",
            docstring='Re-point every reference to ``from_obj`` so it points to ``to_obj`` (M5).\n\nScans all link-type properties (AttachmentSupport, Support, Profile, Base,\nTool, Source, Group, ...) of all document objects and re-points them, making\nrebuilds non-destructive. Subshape names are preserved; mismatches surface\nvia the recompute log. Returns JSON ``{ok, from, to, relinked, count}``.\n\nArgs:\n    doc_name: The document to edit.\n    from_obj: The object whose references are being redirected away from.\n    to_obj: The object references should now point to.',
            signature="(ctx: 'Context', doc_name: 'str', from_obj: 'str', to_obj: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.relink_references_operation",
            rpc_method="relink_references",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_advanced_b",
        ),
        ToolEntry(
            name="restore",
            docstring='Restore a snapshot, replacing the current document in place (I7).\n\nIf ``snapshot_id`` is omitted, the most recent snapshot is restored. The\ncurrent document is closed and the snapshot file is reopened, so the\ndocument is restored in place. Returns JSON\n``{ok, restored_id, doc, new_doc, count}``.\n\nArgs:\n    doc_name: The document to restore into (replaced in place).\n    snapshot_id: Optional snapshot id returned by ``snapshot``; latest if omitted.',
            signature="(ctx: 'Context', doc_name: 'str', snapshot_id: 'str | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.restore_operation",
            rpc_method="restore",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_advanced_b2",
        ),
        ToolEntry(
            name="run_fem_analysis",
            docstring='Run the CalculiX solver on an existing Fem::FemAnalysis container and return summary results.\n\nPrerequisites in the document:\n- A Part-derived solid (e.g. Part::Box, PartDesign::Body) acting as the geometry.\n- A Fem::AnalysisPython container created via `create_object`.\n- A Fem::MaterialCommon assigned to the geometry, added to the analysis.\n- A Fem::FemMeshGmsh referencing the geometry, added to the analysis (the\n  mesh is generated automatically when created via `create_object`).\n- At least one Fem::ConstraintFixed and one Fem::ConstraintForce (or\n  ConstraintPressure) bound to faces of the geometry, added to the analysis.\n\nA SolverCcxTools is auto-created if the analysis has none.\n\nThe solver runs synchronously on the FreeCAD GUI thread and blocks all\nother RPC calls for its duration; do not fan out parallel requests.\n\nReturns max von Mises stress (MPa), max/min displacement (mm), node count,\nand the working directory CalculiX wrote to. On failure, returns the\nprerequisite-check or solver error along with the working directory for\ntriage.\n\nArgs:\n    doc_name: Name of the FreeCAD document.\n    analysis_name: Name of the Fem::AnalysisPython object.\n    timeout: Seconds to wait for the solver (default 600).',
            signature="(ctx: 'Context', doc_name: 'str', analysis_name: 'str', timeout: 'int' = 600) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.run_fem_analysis_operation",
            rpc_method="run_fem_analysis",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=True,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_advanced_b2",
        ),
        ToolEntry(
            name="snapshot",
            docstring='Snapshot the current document into a ring buffer of the last 5 states (I7).\n\nCheap, in-process document copy so a risky step can be undone with one\n``restore`` call. Returns JSON ``{ok, snapshot_id, doc, count}``.\n\nArgs:\n    doc_name: The document to snapshot.',
            signature="(ctx: 'Context', doc_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.snapshot_operation",
            rpc_method="snapshot",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_advanced_b2",
        ),
    ),
)
