"""Emit shadow registration, client stubs, and gateway dispatch artifacts."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .bootstrap import load_frozen_registry_snapshot
from .load import all_subject_manifests
from .schema import SubjectManifest, ToolEntry

_GENERATED_HEADER = (
    '"""GENERATED by freecad_mcp.capabilities.generator — do not edit."""\n\n'
    "from __future__ import annotations\n\n"
)

_CLIENT_STUBS_HEADER = (
    '"""GENERATED by freecad_mcp.capabilities.generator — do not edit.\n\n'
    "INERT PLACEHOLDERS: shadow_client_stubs are registry scaffolding only.\n"
    "They are not faithful FreeCADConnection implementations and must not be\n"
    "copied into production client code (Phase 21).\n"
    '"""\n\n'
    "from __future__ import annotations\n\n"
    "_SHADOW_STUB_NOT_IMPLEMENTED = (\n"
    "    'shadow_client_stubs are inert placeholders; bind via freecad_client_ops'\n"
    ")\n\n"
)


def shadow_output_root() -> Path:
    return Path(__file__).resolve().parents[1] / "generated" / "capabilities"


def _render_client_stub(entry: ToolEntry) -> str:
    mutation_note = entry.mutation_class.value.replace("_", "-")
    lines = [
        f"def {entry.name}(conn, *args, **kwargs):",
        f'    """INERT shadow stub for {entry.name} ({mutation_note})."""',
        "    raise NotImplementedError(_SHADOW_STUB_NOT_IMPLEMENTED)",
    ]
    return "\n".join(lines)


def _render_gateway_entry(entry: ToolEntry) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "tool": entry.name,
        "rpc_method": entry.rpc_method,
        "execution_mode": entry.execution_mode.value,
        "gui_thread": entry.gui_thread,
        "mutation_class": entry.mutation_class.value,
        "operation_path": entry.operation_path,
    }
    if entry.escape_hatch_impl is not None:
        payload["escape_hatch_impl"] = entry.escape_hatch_impl
    return payload


def _export_names() -> tuple[str, ...]:
    from freecad_mcp.server_ops.tool_exports.export_names import __all__ as names

    return tuple(names)


def _bind_part_split(names: tuple[str, ...]) -> tuple[tuple[str, ...], tuple[str, ...]]:
    split_at = "match_subshape"
    if split_at not in names:
        raise ValueError(f"export split marker {split_at!r} missing from export names")
    index = names.index(split_at)
    return names[:index], names[index:]


def render_register_order(register_modules: tuple[str, ...]) -> str:
    lines = [_GENERATED_HEADER.rstrip()]
    for name in register_modules:
        lines.append(f"from freecad_mcp import {name} as _{name}")
    lines.extend(
        [
            "",
            "REGISTER_TOOL_MODULE_OBJECTS = (",
        ]
    )
    for name in register_modules:
        lines.append(f"    _{name},")
    lines.extend(
        [
            ")",
            "",
            "REGISTER_TOOL_MODULES = tuple(",
            "    module.__name__.rsplit('.', maxsplit=1)[-1]",
            "    for module in REGISTER_TOOL_MODULE_OBJECTS",
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def render_production_registration(manifests: tuple[SubjectManifest, ...]) -> str:
    lines = [
        _GENERATED_HEADER.rstrip(),
        "from freecad_mcp.capabilities.load import all_subject_manifests",
        "from freecad_mcp.capabilities.registration_runtime import register_all_manifests",
        "",
        "",
        "def register_tools(mcp, *, dependencies):",
        '    """Register every manifest-declared MCP tool on ``mcp``."""',
        "    return register_all_manifests(",
        "        mcp,",
        "        all_subject_manifests(),",
        "        dependencies=dependencies,",
        "    )",
        "",
        f"# manifest subjects: {', '.join(m.subject for m in manifests)}",
        f"# tool count: {sum(len(m.tools) for m in manifests)}",
        "",
    ]
    return "\n".join(lines)


def render_tool_export_bind_part(
    names: tuple[str, ...],
    *,
    part: int,
) -> str:
    lines = [
        _GENERATED_HEADER.rstrip(),
        "from collections.abc import MutableMapping",
        "from types import SimpleNamespace",
        "",
        "_default_namespace: MutableMapping[str, object] | None = None",
        "",
        "def bind_default_export_namespace(namespace: MutableMapping[str, object]) -> None:",
        "    global _default_namespace",
        "    _default_namespace = namespace",
        "",
        f"def bind_tool_exports_part_{part}(",
        "    exports: dict[str, object],",
        "    namespace: MutableMapping[str, object] | None = None,",
        ") -> None:",
        "    namespace = _default_namespace if namespace is None else namespace",
        "    if namespace is None:",
        "        raise RuntimeError('tool export namespace is not initialized')",
        "    pkg = SimpleNamespace()",
    ]
    for name in names:
        lines.append(f"    pkg.{name} = exports['{name}']")
    lines.extend(["    namespace.update(vars(pkg))", "", ""])
    return "\n".join(lines)


def render_shadow_registration(manifests: tuple[SubjectManifest, ...]) -> str:
    lines = [
        _GENERATED_HEADER.rstrip(),
        "from freecad_mcp.capabilities.load import all_subject_manifests",
        "from freecad_mcp.capabilities.registration_runtime import register_all_manifests",
        "",
        "",
        "def register_shadow_tools(mcp, *, dependencies):",
        '    """Register every bootstrapped manifest entry on ``mcp``."""',
        "    return register_all_manifests(",
        "        mcp,",
        "        all_subject_manifests(),",
        "        dependencies=dependencies,",
        "    )",
        "",
    ]
    lines.append(f"# manifest subjects: {', '.join(m.subject for m in manifests)}")
    lines.append(f"# tool count: {sum(len(m.tools) for m in manifests)}")
    return "\n".join(lines) + "\n"


def render_client_stubs(manifests: tuple[SubjectManifest, ...]) -> str:
    lines = [_CLIENT_STUBS_HEADER.rstrip(), ""]
    for manifest in manifests:
        lines.append(f"# subject: {manifest.subject}")
        for entry in manifest.tools:
            lines.append(_render_client_stub(entry))
            lines.append("")
    return "\n".join(lines)


def render_gateway_dispatch(manifests: tuple[SubjectManifest, ...]) -> dict[str, Any]:
    entries = [
        _render_gateway_entry(entry)
        for manifest in manifests
        for entry in manifest.tools
    ]
    return {
        "tool_count": len(entries),
        "entries": entries,
    }


def write_production_outputs(
    *,
    root: Path | None = None,
    manifests: tuple[SubjectManifest, ...] | None = None,
) -> dict[str, Path]:
    root = root or shadow_output_root()
    root.mkdir(parents=True, exist_ok=True)
    manifests = manifests or all_subject_manifests()
    snapshot = load_frozen_registry_snapshot()
    register_modules = tuple(snapshot["register_order"])
    export_names = _export_names()
    part_1, part_2 = _bind_part_split(export_names)

    paths = {
        "register_order": root / "register_order.py",
        "registration": root / "registration.py",
        "tool_export_bind_part_1": root / "tool_export_bind_part_1.py",
        "tool_export_bind_part_2": root / "tool_export_bind_part_2.py",
    }
    paths["register_order"].write_text(
        render_register_order(register_modules),
        encoding="utf-8",
    )
    paths["registration"].write_text(
        render_production_registration(manifests),
        encoding="utf-8",
    )
    paths["tool_export_bind_part_1"].write_text(
        render_tool_export_bind_part(part_1, part=1),
        encoding="utf-8",
    )
    paths["tool_export_bind_part_2"].write_text(
        render_tool_export_bind_part(part_2, part=2),
        encoding="utf-8",
    )
    return paths


def write_shadow_outputs(
    *,
    root: Path | None = None,
    manifests: tuple[SubjectManifest, ...] | None = None,
    mcp: Any | None = None,
    dependencies: Any | None = None,
) -> dict[str, Path]:
    root = root or shadow_output_root()
    root.mkdir(parents=True, exist_ok=True)
    manifests = manifests or all_subject_manifests()

    paths = write_production_outputs(root=root, manifests=manifests)
    paths.update(
        {
            "shadow_registration": root / "shadow_registration.py",
            "client_stubs": root / "shadow_client_stubs.py",
            "gateway_dispatch": root / "shadow_gateway_dispatch.json",
            "registry_snapshot": root / "registry_snapshot.json",
        }
    )
    paths["shadow_registration"].write_text(
        render_shadow_registration(manifests),
        encoding="utf-8",
    )
    paths["client_stubs"].write_text(
        render_client_stubs(manifests),
        encoding="utf-8",
    )
    paths["gateway_dispatch"].write_text(
        json.dumps(render_gateway_dispatch(manifests), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    if mcp is not None and dependencies is not None:
        from .registration_runtime import register_all_manifests
        from .registry_capture import capture_registry_snapshot

        register_all_manifests(mcp, manifests, dependencies=dependencies)
        snapshot = capture_registry_snapshot(mcp)
        paths["registry_snapshot"].write_text(
            json.dumps(snapshot, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    return paths


__all__ = [
    "render_client_stubs",
    "render_gateway_dispatch",
    "render_production_registration",
    "render_register_order",
    "render_shadow_registration",
    "render_tool_export_bind_part",
    "shadow_output_root",
    "write_production_outputs",
    "write_shadow_outputs",
]
