"""Emit shadow registration, client stubs, and gateway dispatch artifacts."""

from __future__ import annotations

import ast
import hashlib
import json
import re
from pathlib import Path
from typing import Any

from .bootstrap import load_frozen_registry_snapshot
from .load import all_subject_manifests
from .schema import SubjectManifest, ToolEntry

_GENERATED_HEADER = (
    '"""GENERATED by freecad_mcp.capabilities.generator — do not edit."""\n\n'
    "from __future__ import annotations\n\n"
)

_CLIENT_STUBS_HEADER = (
    '"""GENERATED by freecad_mcp.capabilities.generator — do not edit.\n\n'
    "INERT PLACEHOLDERS: shadow_client_stubs are registry scaffolding only.\n"
    "They are not faithful FreeCADConnection implementations and must not be\n"
    "copied into production client code (Phase 21).\n"
    '"""\n\n'
    "from __future__ import annotations\n\n"
    "_SHADOW_STUB_NOT_IMPLEMENTED = (\n"
    "    'shadow_client_stubs are inert placeholders; bind via freecad_client_ops'\n"
    ")\n\n"
)

_PRODUCTION_CLIENT_STUBS_HEADER = (
    '"""GENERATED by freecad_mcp.capabilities.generator — do not edit.\n\n'
    "Production client stubs delegate to generated connection methods when a\n"
    "FreeCADConnection RPC binding exists; template-only tools remain inert.\n"
    '"""\n\n'
    "from __future__ import annotations\n\n"
    "_CLIENT_STUB_NOT_IMPLEMENTED = (\n"
    "    'client stub has no generated FreeCADConnection binding; use MCP operation'\n"
    ")\n\n"
)


def shadow_output_root() -> Path:
    return Path(__file__).resolve().parents[1] / "generated" / "capabilities"


def _package_root() -> Path:
    return Path(__file__).resolve().parents[1]


def register_modules_root() -> Path:
    return shadow_output_root() / "register_modules"


def inline_output_root() -> Path:
    return shadow_output_root() / "inline"


def connection_methods_root() -> Path:
    return shadow_output_root() / "connection_methods"


def addon_gateway_dispatch_root() -> Path:
    return _repository_root() / "addon" / "FreeCADMCP" / "generated" / "capabilities"


def _repository_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _hand_written_connection_methods_dir() -> Path:
    return _package_root() / "freecad_client_ops" / "connection_methods"


def connection_method_module_names() -> tuple[str, ...]:
    return tuple(
        sorted(
            path.stem
            for path in _hand_written_connection_methods_dir().glob("*.py")
            if path.stem != "__init__"
        )
    )


def _strip_hand_written_prologue(source: str) -> str:  # noqa: C901
    """Drop module docstrings, ``from __future__``, and ruff noqa prologue lines."""

    lines = source.splitlines()
    index = 0

    def _skip_docstring(start: int) -> int:
        if start >= len(lines):
            return start
        first = lines[start].strip()
        if not first.startswith(("'''", '"""')):
            return start
        quote = first[:3]
        if first.count(quote) >= 2 and len(first) > 3:
            return start + 1
        for offset in range(start + 1, len(lines)):
            if quote in lines[offset]:
                return offset + 1
        return start

    index = _skip_docstring(index)
    while index < len(lines) and not lines[index].strip():
        index += 1
    while index < len(lines):
        stripped = lines[index].strip()
        if stripped == "from __future__ import annotations":
            index += 1
            while index < len(lines) and not lines[index].strip():
                index += 1
            continue
        if stripped.startswith("# ruff:"):
            index += 1
            continue
        break
    index = _skip_docstring(index)
    while index < len(lines) and not lines[index].strip():
        index += 1
    return "\n".join(lines[index:]).rstrip() + "\n"


def _rewrite_package_imports(body: str) -> str:
    """Rewrite ``freecad_mcp`` sibling imports for generated register modules."""

    import re

    body = re.sub(r"^(\s*)from \.\.", r"\1from freecad_mcp.", body, flags=re.MULTILINE)
    return re.sub(r"^(\s*)from \.", r"\1from freecad_mcp.", body, flags=re.MULTILINE)


def _bindings_from_source(source: str) -> tuple[str, ...]:
    """Return all module-level function and class names."""

    tree = ast.parse(source)
    names: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            names.append(node.name)
    return tuple(names)


def _public_bindings_from_source(source: str) -> tuple[str, ...]:
    """Return module-level public function and class names."""

    return tuple(
        name for name in _bindings_from_source(source) if not name.startswith("_")
    )


def relocated_body_digest(source: str) -> str:
    """Return a stable SHA-256 digest for a relocated module body."""

    normalized = source.rstrip() + "\n"
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def relocated_body_digests_fixture_path() -> Path:
    return _repository_root() / "tests" / "fixtures" / "capability_relocated_body_digests.json"


def load_relocated_body_digests() -> dict[str, dict[str, str]]:
    path = relocated_body_digests_fixture_path()
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {
        "register_modules": dict(payload["register_modules"]),
        "connection_methods": dict(payload["connection_methods"]),
    }


def relocated_register_module_body(module_name: str) -> str:
    path = register_modules_root() / f"{module_name}.py"
    return _strip_generated_header(path.read_text(encoding="utf-8"))


def relocated_connection_method_body(module_name: str) -> str:
    path = connection_methods_root() / f"{module_name}.py"
    return _strip_generated_header(path.read_text(encoding="utf-8"))


def current_relocated_body_digests(
    *,
    register_modules: tuple[str, ...] | None = None,
    connection_modules: tuple[str, ...] | None = None,
) -> dict[str, dict[str, str]]:
    register_modules = register_modules or tuple(
        load_frozen_registry_snapshot()["register_order"]
    )
    connection_modules = connection_modules or connection_method_module_names()
    return {
        "register_modules": {
            module_name: relocated_body_digest(relocated_register_module_body(module_name))
            for module_name in register_modules
        },
        "connection_methods": {
            module_name: relocated_body_digest(
                relocated_connection_method_body(module_name)
            )
            for module_name in connection_modules
        },
    }


def _strip_generated_header(source: str) -> str:
    if not source.startswith('"""GENERATED'):
        return source
    lines = source.splitlines()
    index = 0
    if lines:
        index = 1
        if lines[0].count('"""') < 2:
            for offset in range(1, len(lines)):
                if '"""' in lines[offset]:
                    index = offset + 1
                    break
    while index < len(lines) and not lines[index].strip():
        index += 1
    if index < len(lines) and lines[index].strip() == "from __future__ import annotations":
        index += 1
    while index < len(lines) and not lines[index].strip():
        index += 1
    return "\n".join(lines[index:]).rstrip() + "\n"


def render_register_module(module_name: str, source: str) -> str:
    body = _rewrite_package_imports(_strip_hand_written_prologue(source))
    return _GENERATED_HEADER.rstrip() + "\n" + body + "\n"


def render_inline_tools_runtime_info(source: str) -> str:
    body = _rewrite_package_imports(_strip_hand_written_prologue(source))
    register_index = body.rfind("\ndef register(")
    if register_index != -1:
        body = body[:register_index].rstrip() + "\n"
    body += (
        "\n\n"
        "def get_runtime_info(ctx: Context) -> CallToolResult:\n"
        '    """Report exact MCP, addon, FreeCAD, RPC, and isolated-profile identity."""'
        "\n\n"
        "    return json_response(\n"
        "        _runtime_info_payload(),\n"
        "        message='Connected FreeCAD MCP runtime identity',\n"
        "    )\n"
    )
    return _GENERATED_HEADER.rstrip() + "\n" + body + "\n"


def render_register_module_shim(module_name: str) -> str:
    return (
        '"""Declarative shim — generated register module lives in generated/capabilities."""\n\n'
        f"from freecad_mcp.generated.capabilities.register_modules.{module_name} "
        "import register\n\n"
        "__all__ = ['register']\n"
    )


def render_inline_tools_runtime_info_shim() -> str:
    return (
        '"""Declarative shim — inline runtime info lives in generated/capabilities."""\n\n'
        "from freecad_mcp.generated.capabilities.inline.tools_runtime_info import (\n"
        "    get_runtime_info,\n"
        "    _compatibility_for_manifest,\n"
        "    _runtime_info_payload,\n"
        ")\n\n"
        "__all__ = [\n"
        "    'get_runtime_info',\n"
        "    '_compatibility_for_manifest',\n"
        "    '_runtime_info_payload',\n"
        "]\n"
    )


def _read_register_module_source(module_name: str) -> str:
    """Read the canonical relocated body used to (re)emit generated register modules."""

    generated_path = register_modules_root() / f"{module_name}.py"
    if generated_path.is_file():
        return relocated_register_module_body(module_name)
    hand_written_path = _package_root() / f"{module_name}.py"
    if hand_written_path.is_file():
        return hand_written_path.read_text(encoding="utf-8")
    raise FileNotFoundError(f"register module source missing for {module_name!r}")


def write_register_module_outputs(
    *,
    root: Path | None = None,
    register_modules: tuple[str, ...] | None = None,
) -> dict[str, Path]:
    root = root or shadow_output_root()
    register_modules = register_modules or tuple(
        load_frozen_registry_snapshot()["register_order"]
    )
    modules_dir = root / "register_modules"
    inline_dir = root / "inline"
    modules_dir.mkdir(parents=True, exist_ok=True)
    inline_dir.mkdir(parents=True, exist_ok=True)
    (modules_dir / "__init__.py").write_text(
        '"""GENERATED register modules for MCP tool registration."""\n',
        encoding="utf-8",
    )
    (inline_dir / "__init__.py").write_text(
        '"""GENERATED inline tool references for manifest metadata."""\n',
        encoding="utf-8",
    )

    paths: dict[str, Path] = {}
    for module_name in register_modules:
        source = _read_register_module_source(module_name)
        path = modules_dir / f"{module_name}.py"
        path.write_text(render_register_module(module_name, source), encoding="utf-8")
        paths[f"register_module:{module_name}"] = path

    runtime_info_source = _read_register_module_source("tools_runtime_info")
    inline_path = inline_dir / "tools_runtime_info.py"
    inline_path.write_text(
        render_inline_tools_runtime_info(runtime_info_source),
        encoding="utf-8",
    )
    paths["inline:tools_runtime_info"] = inline_path
    return paths


def _rewrite_connection_method_imports(body: str) -> str:
    """Rewrite parent-package imports for generated connection methods."""

    body = re.sub(
        r"^(\s*)from \.\.\.(\w+)",
        r"\1from freecad_mcp.\2",
        body,
        flags=re.MULTILINE,
    )
    return re.sub(
        r"^(\s*)from \.\.(\w+)",
        r"\1from freecad_mcp.freecad_client_ops.\2",
        body,
        flags=re.MULTILINE,
    )


def render_connection_method(module_name: str, source: str) -> str:
    body = _rewrite_connection_method_imports(_strip_hand_written_prologue(source))
    return _GENERATED_HEADER.rstrip() + "\n" + body + "\n"


def render_connection_method_shim(
    module_name: str,
    *,
    exports: tuple[str, ...] | None = None,
) -> str:
    if exports is None:
        exports = _bindings_from_source(_read_connection_method_source(module_name))
    if not exports:
        return (
            '"""Declarative shim — generated connection method lives in '
            'generated/capabilities."""\n\n'
            "__all__: list[str] = []\n"
        )
    lines = [
        '"""Declarative shim — generated connection method lives in generated/capabilities."""',
        "",
        "from freecad_mcp.generated.capabilities.connection_methods import (",
        f"    {module_name} as _generated,",
        ")",
        "",
    ]
    all_marker = "  # noqa: RUF022" if tuple(exports) != tuple(sorted(exports)) else ""
    lines.extend(f"{name} = _generated.{name}" for name in exports)
    lines.extend(
        [
            "",
            f"__all__ = [{all_marker}",
        ]
    )
    lines.extend(f"    {name!r}," for name in exports)
    lines.append("]")
    return "\n".join(lines) + "\n"


def render_connection_methods_package_init(
    module_names: tuple[str, ...] | None = None,
) -> str:
    module_names = module_names or connection_method_module_names()
    lines = ['"""Re-export connection method implementations."""', ""]
    all_exports: list[str] = []
    for module_name in module_names:
        exports = tuple(
            sorted(
                _public_bindings_from_source(
                    _read_connection_method_source(module_name)
                )
            )
        )
        if not exports:
            continue
        lines.append(f"from .{module_name} import (")
        lines.extend(f"    {name}," for name in exports)
        lines.append(")")
        all_exports.extend(exports)
    lines.extend(["", "__all__ = ["])
    lines.extend(f"    {name!r}," for name in sorted(all_exports))
    lines.append("]")
    return "\n".join(lines) + "\n"


def _read_connection_method_source(module_name: str) -> str:
    """Read the canonical relocated body used to (re)emit generated connection methods."""

    generated_path = connection_methods_root() / f"{module_name}.py"
    if generated_path.is_file():
        return relocated_connection_method_body(module_name)
    hand_written_path = _hand_written_connection_methods_dir() / f"{module_name}.py"
    if hand_written_path.is_file():
        return hand_written_path.read_text(encoding="utf-8")
    raise FileNotFoundError(f"connection method source missing for {module_name!r}")


def _rpc_method_connection_modules() -> dict[str, str]:
    mapping: dict[str, str] = {}
    for module_name in connection_method_module_names():
        if not module_name.startswith("connection_"):
            continue
        source = _read_connection_method_source(module_name)
        tree = ast.parse(source)
        for node in tree.body:
            if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
                mapping[node.name] = module_name
    return mapping


def write_connection_method_outputs(
    *,
    root: Path | None = None,
    module_names: tuple[str, ...] | None = None,
) -> dict[str, Path]:
    root = root or shadow_output_root()
    module_names = module_names or connection_method_module_names()
    modules_dir = root / "connection_methods"
    modules_dir.mkdir(parents=True, exist_ok=True)
    (modules_dir / "__init__.py").write_text(
        '"""GENERATED FreeCADConnection RPC method implementations."""\n',
        encoding="utf-8",
    )

    paths: dict[str, Path] = {}
    for module_name in module_names:
        source = _read_connection_method_source(module_name)
        path = modules_dir / f"{module_name}.py"
        path.write_text(render_connection_method(module_name, source), encoding="utf-8")
        paths[f"connection_method:{module_name}"] = path
    return paths


def _write_gateway_dispatch_json(path: Path, manifests: tuple[SubjectManifest, ...]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(render_gateway_dispatch(manifests), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def write_addon_gateway_dispatch(
    *,
    manifests: tuple[SubjectManifest, ...] | None = None,
) -> Path:
    manifests = manifests or all_subject_manifests()
    path = addon_gateway_dispatch_root() / "gateway_dispatch.json"
    _write_gateway_dispatch_json(path, manifests)
    (addon_gateway_dispatch_root() / "__init__.py").write_text(
        '"""GENERATED gateway dispatch metadata for the add-on."""\n',
        encoding="utf-8",
    )
    return path


def _render_client_stub(entry: ToolEntry) -> str:
    mutation_note = entry.mutation_class.value.replace("_", "-")
    lines = [
        f"def {entry.name}(conn, *args, **kwargs):",
        f'    """INERT shadow stub for {entry.name} ({mutation_note})."""',
        "    raise NotImplementedError(_SHADOW_STUB_NOT_IMPLEMENTED)",
    ]
    return "\n".join(lines)


def _render_production_client_stub(
    entry: ToolEntry,
    *,
    connection_modules: dict[str, str],
) -> str:
    mutation_note = entry.mutation_class.value.replace("_", "-")
    module_name = connection_modules.get(entry.rpc_method)
    if module_name is None:
        lines = [
            f"def {entry.name}(conn, *args, **kwargs):",
            f'    """Generated client stub for {entry.name} ({mutation_note})."""',
            "    raise NotImplementedError(_CLIENT_STUB_NOT_IMPLEMENTED)",
        ]
        return "\n".join(lines)
    lines = [
        f"def {entry.name}(conn, *args, **kwargs):",
        f'    """Generated client stub for {entry.name} ({mutation_note})."""',
        f"    from freecad_mcp.generated.capabilities.connection_methods.{module_name} import (",
        f"        {entry.rpc_method} as _impl,",
        "    )",
        "    return _impl(conn, *args, **kwargs)",
    ]
    return "\n".join(lines)


def _render_gateway_entry(entry: ToolEntry) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "tool": entry.name,
        "rpc_method": entry.rpc_method,
        "execution_mode": entry.execution_mode.value,
        "gui_thread": entry.gui_thread,
        "mutation_class": entry.mutation_class.value,
        "operation_path": entry.operation_path,
    }
    if entry.escape_hatch_impl is not None:
        payload["escape_hatch_impl"] = entry.escape_hatch_impl
    return payload


def _export_names() -> tuple[str, ...]:
    from freecad_mcp.server_ops.tool_exports.export_names import __all__ as names

    return tuple(names)


def _bind_part_split(names: tuple[str, ...]) -> tuple[tuple[str, ...], tuple[str, ...]]:
    split_at = "match_subshape"
    if split_at not in names:
        raise ValueError(f"export split marker {split_at!r} missing from export names")
    index = names.index(split_at)
    return names[:index], names[index:]


def render_register_order(register_modules: tuple[str, ...]) -> str:
    lines = [_GENERATED_HEADER.rstrip()]
    for name in register_modules:
        lines.append(f"from freecad_mcp import {name} as _{name}")
    lines.extend(
        [
            "",
            "REGISTER_TOOL_MODULE_OBJECTS = (",
        ]
    )
    for name in register_modules:
        lines.append(f"    _{name},")
    lines.extend(
        [
            ")",
            "",
            "REGISTER_TOOL_MODULES = tuple(",
            "    module.__name__.rsplit('.', maxsplit=1)[-1]",
            "    for module in REGISTER_TOOL_MODULE_OBJECTS",
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def render_production_registration(manifests: tuple[SubjectManifest, ...]) -> str:
    lines = [
        _GENERATED_HEADER.rstrip(),
        "from freecad_mcp.capabilities.load import all_subject_manifests",
        "from freecad_mcp.capabilities.registration_runtime import register_all_manifests",
        "",
        "",
        "def register_tools(mcp, *, dependencies):",
        '    """Register every manifest-declared MCP tool on ``mcp``."""',
        "    return register_all_manifests(",
        "        mcp,",
        "        all_subject_manifests(),",
        "        dependencies=dependencies,",
        "    )",
        "",
        f"# manifest subjects: {', '.join(m.subject for m in manifests)}",
        f"# tool count: {sum(len(m.tools) for m in manifests)}",
        "",
    ]
    return "\n".join(lines)


def render_tool_export_bind_part(
    names: tuple[str, ...],
    *,
    part: int,
) -> str:
    lines = [
        _GENERATED_HEADER.rstrip(),
        "from collections.abc import MutableMapping",
        "from types import SimpleNamespace",
        "",
        "_default_namespace: MutableMapping[str, object] | None = None",
        "",
        "def bind_default_export_namespace(namespace: MutableMapping[str, object]) -> None:",
        "    global _default_namespace",
        "    _default_namespace = namespace",
        "",
        f"def bind_tool_exports_part_{part}(",
        "    exports: dict[str, object],",
        "    namespace: MutableMapping[str, object] | None = None,",
        ") -> None:",
        "    namespace = _default_namespace if namespace is None else namespace",
        "    if namespace is None:",
        "        raise RuntimeError('tool export namespace is not initialized')",
        "    pkg = SimpleNamespace()",
    ]
    for name in names:
        lines.append(f"    pkg.{name} = exports['{name}']")
    lines.extend(["    namespace.update(vars(pkg))", "", ""])
    return "\n".join(lines)


def render_shadow_registration(manifests: tuple[SubjectManifest, ...]) -> str:
    lines = [
        _GENERATED_HEADER.rstrip(),
        "from freecad_mcp.capabilities.load import all_subject_manifests",
        "from freecad_mcp.capabilities.registration_runtime import register_all_manifests",
        "",
        "",
        "def register_shadow_tools(mcp, *, dependencies):",
        '    """Register every bootstrapped manifest entry on ``mcp``."""',
        "    return register_all_manifests(",
        "        mcp,",
        "        all_subject_manifests(),",
        "        dependencies=dependencies,",
        "    )",
        "",
    ]
    lines.append(f"# manifest subjects: {', '.join(m.subject for m in manifests)}")
    lines.append(f"# tool count: {sum(len(m.tools) for m in manifests)}")
    return "\n".join(lines) + "\n"


def render_client_stubs(manifests: tuple[SubjectManifest, ...]) -> str:
    lines = [_CLIENT_STUBS_HEADER.rstrip(), ""]
    for manifest in manifests:
        lines.append(f"# subject: {manifest.subject}")
        for entry in manifest.tools:
            lines.append(_render_client_stub(entry))
            lines.append("")
    return "\n".join(lines)


def render_production_client_stubs(manifests: tuple[SubjectManifest, ...]) -> str:
    connection_modules = _rpc_method_connection_modules()
    lines = [_PRODUCTION_CLIENT_STUBS_HEADER.rstrip(), ""]
    for manifest in manifests:
        lines.append(f"# subject: {manifest.subject}")
        for entry in manifest.tools:
            lines.append(
                _render_production_client_stub(
                    entry,
                    connection_modules=connection_modules,
                )
            )
            lines.append("")
    return "\n".join(lines)


def render_gateway_dispatch(manifests: tuple[SubjectManifest, ...]) -> dict[str, Any]:
    entries = [
        _render_gateway_entry(entry)
        for manifest in manifests
        for entry in manifest.tools
    ]
    return {
        "tool_count": len(entries),
        "entries": entries,
    }


def write_production_outputs(
    *,
    root: Path | None = None,
    manifests: tuple[SubjectManifest, ...] | None = None,
) -> dict[str, Path]:
    root = root or shadow_output_root()
    root.mkdir(parents=True, exist_ok=True)
    manifests = manifests or all_subject_manifests()
    snapshot = load_frozen_registry_snapshot()
    register_modules = tuple(snapshot["register_order"])
    export_names = _export_names()
    part_1, part_2 = _bind_part_split(export_names)

    paths = {
        "register_order": root / "register_order.py",
        "registration": root / "registration.py",
        "tool_export_bind_part_1": root / "tool_export_bind_part_1.py",
        "tool_export_bind_part_2": root / "tool_export_bind_part_2.py",
        "client_stubs": root / "client_stubs.py",
        "gateway_dispatch": root / "gateway_dispatch.json",
    }
    paths["register_order"].write_text(
        render_register_order(register_modules),
        encoding="utf-8",
    )
    paths["registration"].write_text(
        render_production_registration(manifests),
        encoding="utf-8",
    )
    paths["tool_export_bind_part_1"].write_text(
        render_tool_export_bind_part(part_1, part=1),
        encoding="utf-8",
    )
    paths["tool_export_bind_part_2"].write_text(
        render_tool_export_bind_part(part_2, part=2),
        encoding="utf-8",
    )
    paths["client_stubs"].write_text(
        render_production_client_stubs(manifests),
        encoding="utf-8",
    )
    _write_gateway_dispatch_json(paths["gateway_dispatch"], manifests)
    paths.update(write_register_module_outputs(root=root, register_modules=register_modules))
    paths.update(write_connection_method_outputs(root=root))
    paths["addon_gateway_dispatch"] = write_addon_gateway_dispatch(manifests=manifests)
    return paths


def write_shadow_outputs(
    *,
    root: Path | None = None,
    manifests: tuple[SubjectManifest, ...] | None = None,
    mcp: Any | None = None,
    dependencies: Any | None = None,
) -> dict[str, Path]:
    root = root or shadow_output_root()
    root.mkdir(parents=True, exist_ok=True)
    manifests = manifests or all_subject_manifests()

    paths = write_production_outputs(root=root, manifests=manifests)
    paths.update(
        {
            "shadow_registration": root / "shadow_registration.py",
            "shadow_client_stubs": root / "shadow_client_stubs.py",
            "shadow_gateway_dispatch": root / "shadow_gateway_dispatch.json",
            "registry_snapshot": root / "registry_snapshot.json",
        }
    )
    paths["shadow_registration"].write_text(
        render_shadow_registration(manifests),
        encoding="utf-8",
    )
    paths["shadow_client_stubs"].write_text(
        render_client_stubs(manifests),
        encoding="utf-8",
    )
    _write_gateway_dispatch_json(paths["shadow_gateway_dispatch"], manifests)

    if mcp is not None and dependencies is not None:
        from .registration_runtime import register_all_manifests
        from .registry_capture import capture_registry_snapshot

        register_all_manifests(mcp, manifests, dependencies=dependencies)
        snapshot = capture_registry_snapshot(mcp)
        paths["registry_snapshot"].write_text(
            json.dumps(snapshot, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    return paths


__all__ = [
    "addon_gateway_dispatch_root",
    "connection_method_module_names",
    "connection_methods_root",
    "current_relocated_body_digests",
    "inline_output_root",
    "load_relocated_body_digests",
    "register_modules_root",
    "relocated_body_digest",
    "relocated_body_digests_fixture_path",
    "relocated_connection_method_body",
    "relocated_register_module_body",
    "render_client_stubs",
    "render_connection_method",
    "render_connection_method_shim",
    "render_connection_methods_package_init",
    "render_gateway_dispatch",
    "render_inline_tools_runtime_info",
    "render_inline_tools_runtime_info_shim",
    "render_production_client_stubs",
    "render_production_registration",
    "render_register_module",
    "render_register_module_shim",
    "render_register_order",
    "render_shadow_registration",
    "render_tool_export_bind_part",
    "shadow_output_root",
    "write_addon_gateway_dispatch",
    "write_connection_method_outputs",
    "write_production_outputs",
    "write_register_module_outputs",
    "write_shadow_outputs",
]
