"""Emit shadow registration, client stubs, and gateway dispatch artifacts."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .load import all_subject_manifests
from .registry_capture import capture_registry_snapshot
from .schema import SubjectManifest, ToolEntry

_GENERATED_HEADER = (
    '"""GENERATED by freecad_mcp.capabilities.generator — do not edit."""\n\n'
    "from __future__ import annotations\n\n"
)

_CLIENT_STUBS_HEADER = (
    '"""GENERATED by freecad_mcp.capabilities.generator — do not edit.\n\n'
    "INERT PLACEHOLDERS: shadow_client_stubs are registry scaffolding only.\n"
    "They are not faithful FreeCADConnection implementations and must not be\n"
    "copied into production client code (Phase 21).\n"
    '"""\n\n'
    "from __future__ import annotations\n\n"
    "_SHADOW_STUB_NOT_IMPLEMENTED = (\n"
    "    'shadow_client_stubs are inert placeholders; bind via freecad_client_ops'\n"
    ")\n\n"
)


def shadow_output_root() -> Path:
    return Path(__file__).resolve().parents[1] / "generated" / "capabilities"


def _render_client_stub(entry: ToolEntry) -> str:
    mutation_note = entry.mutation_class.value.replace("_", "-")
    lines = [
        f"def {entry.name}(conn, *args, **kwargs):",
        f'    """INERT shadow stub for {entry.name} ({mutation_note})."""',
        "    raise NotImplementedError(_SHADOW_STUB_NOT_IMPLEMENTED)",
    ]
    return "\n".join(lines)


def _render_gateway_entry(entry: ToolEntry) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "tool": entry.name,
        "rpc_method": entry.rpc_method,
        "execution_mode": entry.execution_mode.value,
        "gui_thread": entry.gui_thread,
        "mutation_class": entry.mutation_class.value,
        "operation_path": entry.operation_path,
    }
    if entry.escape_hatch_impl is not None:
        payload["escape_hatch_impl"] = entry.escape_hatch_impl
    return payload


def render_shadow_registration(manifests: tuple[SubjectManifest, ...]) -> str:
    lines = [
        _GENERATED_HEADER.rstrip(),
        "from freecad_mcp.capabilities.load import all_subject_manifests",
        "from freecad_mcp.capabilities.registration_runtime import register_all_manifests",
        "",
        "",
        "def register_shadow_tools(mcp, *, dependencies):",
        '    """Register every bootstrapped manifest entry on ``mcp``."""',
        "    return register_all_manifests(",
        "        mcp,",
        "        all_subject_manifests(),",
        "        dependencies=dependencies,",
        "    )",
        "",
    ]
    lines.append(f"# manifest subjects: {', '.join(m.subject for m in manifests)}")
    lines.append(f"# tool count: {sum(len(m.tools) for m in manifests)}")
    return "\n".join(lines) + "\n"


def render_client_stubs(manifests: tuple[SubjectManifest, ...]) -> str:
    lines = [_CLIENT_STUBS_HEADER.rstrip(), ""]
    for manifest in manifests:
        lines.append(f"# subject: {manifest.subject}")
        for entry in manifest.tools:
            lines.append(_render_client_stub(entry))
            lines.append("")
    return "\n".join(lines)


def render_gateway_dispatch(manifests: tuple[SubjectManifest, ...]) -> dict[str, Any]:
    entries = [
        _render_gateway_entry(entry)
        for manifest in manifests
        for entry in manifest.tools
    ]
    return {
        "tool_count": len(entries),
        "entries": entries,
    }


def write_shadow_outputs(
    *,
    root: Path | None = None,
    manifests: tuple[SubjectManifest, ...] | None = None,
    mcp: Any | None = None,
    dependencies: Any | None = None,
) -> dict[str, Path]:
    root = root or shadow_output_root()
    root.mkdir(parents=True, exist_ok=True)
    manifests = manifests or all_subject_manifests()

    paths = {
        "registration": root / "shadow_registration.py",
        "client_stubs": root / "shadow_client_stubs.py",
        "gateway_dispatch": root / "shadow_gateway_dispatch.json",
        "registry_snapshot": root / "registry_snapshot.json",
    }
    paths["registration"].write_text(
        render_shadow_registration(manifests),
        encoding="utf-8",
    )
    paths["client_stubs"].write_text(
        render_client_stubs(manifests),
        encoding="utf-8",
    )
    paths["gateway_dispatch"].write_text(
        json.dumps(render_gateway_dispatch(manifests), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    if mcp is not None and dependencies is not None:
        from .registration_runtime import register_all_manifests

        register_all_manifests(mcp, manifests, dependencies=dependencies)
        snapshot = capture_registry_snapshot(mcp)
        paths["registry_snapshot"].write_text(
            json.dumps(snapshot, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    return paths


__all__ = [
    "render_client_stubs",
    "render_gateway_dispatch",
    "render_shadow_registration",
    "shadow_output_root",
    "write_shadow_outputs",
]
