"""Compatibility imports for canonical protocol validation helpers."""

try:
    from ..._shared.protocol.validation import (
        _format_utc,
        _is_uuid,
        _limited_canonical_json,
        _normalize_features,
        _parse_utc,
        _require_exact_keys,
        _require_host,
        _require_identifier,
        _require_pid,
        _require_port,
        _require_sequence,
        _require_string,
        _require_uuid,
        _token_digest,
        _validate_json_value,
        _validate_nonce,
        _validate_secret,
        _validate_token,
        canonical_json_bytes,
    )
except ImportError:
    from _shared.protocol.validation import (
        _format_utc,
        _is_uuid,
        _limited_canonical_json,
        _normalize_features,
        _parse_utc,
        _require_exact_keys,
        _require_host,
        _require_identifier,
        _require_pid,
        _require_port,
        _require_sequence,
        _require_string,
        _require_uuid,
        _token_digest,
        _validate_json_value,
        _validate_nonce,
        _validate_secret,
        _validate_token,
        canonical_json_bytes,
    )

__all__ = [
    "_format_utc",
    "_is_uuid",
    "_limited_canonical_json",
    "_normalize_features",
    "_parse_utc",
    "_require_exact_keys",
    "_require_host",
    "_require_identifier",
    "_require_pid",
    "_require_port",
    "_require_sequence",
    "_require_string",
    "_require_uuid",
    "_token_digest",
    "_validate_json_value",
    "_validate_nonce",
    "_validate_secret",
    "_validate_token",
    "canonical_json_bytes",
]
