#!/usr/bin/env python3
"""Generate matching package/addon build metadata for CI or release builds."""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build_metadata(
    *,
    version: str,
    git_commit: str = "unknown",
    dirty: bool = False,
    timestamp: str | None = None,
) -> dict[str, object]:
    resolved_timestamp = timestamp or (
        datetime.now(UTC)
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z")
    )
    suffix = git_commit[:12] if git_commit != "unknown" else "unknown"
    if dirty and git_commit != "unknown":
        suffix += ".dirty"
    git_dirty = None if git_commit == "unknown" else bool(dirty)
    return {
        "version": version,
        "git_commit": git_commit,
        "git_dirty": git_dirty,
        "build_timestamp": resolved_timestamp,
        "build_id": f"freecad-mcp-{version}+{suffix}",
    }


def render_python(metadata: dict[str, object]) -> str:
    return (
        '"""Generated by scripts/generate_build_metadata.py; do not edit."""\n\n'
        f"GIT_COMMIT = {metadata['git_commit']!r}\n"
        f"GIT_DIRTY = {metadata['git_dirty']!r}\n"
        f"BUILD_TIMESTAMP = {metadata['build_timestamp']!r}\n"
        f"BUILD_ID = {metadata['build_id']!r}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--git-commit", default="unknown")
    parser.add_argument("--dirty", action="store_true")
    parser.add_argument("--timestamp")
    args = parser.parse_args()
    metadata = build_metadata(
        version=args.version,
        git_commit=args.git_commit,
        dirty=args.dirty,
        timestamp=args.timestamp,
    )
    package_path = ROOT / "src" / "freecad_mcp" / "_build_metadata.py"
    addon_path = ROOT / "addon" / "FreeCADMCP" / "_build_metadata.json"
    package_path.write_text(render_python(metadata), encoding="utf-8")
    addon_path.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(metadata["build_id"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
