"""Capability manifest for lease (bootstrapped)."""

from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="lease",
    register_modules=('tools_lease_acquire_a', 'tools_lease_acquire_b', 'tools_lease_lifecycle'),
    tools=(
        ToolEntry(
            name="acquire_document_lock",
            docstring='Acquire an exclusive renewable write lease for a FreeCAD document.\n\nPrefer ``selector`` with an addon-issued ``document_session_uuid`` plus\noptional name/path assertions. All supplied selector fields must resolve to\nthe same open document; ActiveDocument is never used. The one-time private\ncredential is retained by this MCP process for later calls.\n\n``doc_name``, ``file_path``, and ``session_id`` are deprecated selector\naliases. They still acquire through the authenticated protocol-v2 service\nand produce the same canonical schema-v2 sidecar as ``selector``.',
            signature='(ctx: \'Context\', doc_name: \'str\' = \'\', file_path: \'str\' = \'\', session_id: \'str\' = \'\', task_description: \'str\' = \'\', selector: \'DocumentSelectorInput | None\' = None, agent_id: \'str\' = \'\', hash_policy: "Literal[\'sha256\']" = \'sha256\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.capabilities.legacy_shims.legacy_removed_tool",
            rpc_method="acquire_document_lock",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_acquire_a",
        ),
        ToolEntry(
            name="adopt_dirty_document",
            docstring="Adopt existing unsaved changes into the verified lease-v2 lifecycle.\n\nThe selector must contain ``document_name``, ``document_session_uuid``, or\n``canonical_path``. Initial adoption of an unlocked dirty document is\nauto-authorized (no FreeCAD pop-up). Taking over another agent's dirty\n``LOCKED_ERROR`` lease is also auto-authorized without a FreeCAD pop-up.\nThe bounded handoff runs asynchronously while the tool returns a non-error\n``LOCKED_ERROR_HANDOFF_PENDING`` result with a ``request_id``. Resume with\n``get_request_status`` then\n``claim_acquisition_result`` (same path as transport loss).\n``cancel_request`` aborts the handoff before CAS. Adoption creates a\nrecovery snapshot before this MCP process receives the lease credential.\nThe main FCStd is not saved by adoption.",
            signature='(ctx: \'Context\', selector: \'DocumentSelectorInput\', task_description: \'str\' = \'\', agent_id: \'str\' = \'\', hash_policy: "Literal[\'sha256\']" = \'sha256\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.capabilities.legacy_shims.legacy_removed_tool",
            rpc_method="adopt_dirty_document",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_acquire_a",
        ),
        ToolEntry(
            name="get_document_lock",
            docstring='Return redacted effective local/foreign lease state for one document.\n\nPrefer ``selector``. The legacy identity arguments remain temporarily for\noff/observe migration compatibility. Status never includes the bearer token\nor its fingerprint; malformed or conflicting sidecars report locked/unknown.',
            signature="(ctx: 'Context', doc_name: 'str' = '', file_path: 'str' = '', session_id: 'str' = '', selector: 'DocumentSelectorInput | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.capabilities.legacy_shims.legacy_removed_tool",
            rpc_method="get_document_lock",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_acquire_a",
        ),
        ToolEntry(
            name="list_document_locks",
            docstring='List redacted local, foreign, stale, error, and dirty-recovery records.\n\nThe response contains no bearer tokens or token fingerprints.',
            signature="(ctx: 'Context') -> 'CallToolResult'",
            operation_path="freecad_mcp.capabilities.legacy_shims.legacy_removed_tool",
            rpc_method="list_document_locks",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_acquire_a",
        ),
        ToolEntry(
            name="release_document_lock",
            docstring='CAS-release only a clean, verified saved/restored document lease.\n\nPrefer ``selector``; its credential is selected from private MCP memory.\n``doc_key`` and ``token`` are deprecated protocol-v1 compatibility fields\nfor off/observe migration only and are rejected for enforce-mode mutation.\nAgents cannot use this tool for dirty abandonment.',
            signature='(ctx: \'Context\', selector: \'DocumentSelectorInput | None\' = None, disposition: "Literal[\'saved\', \'restored\']" = \'saved\', doc_key: \'str\' = \'\', token: \'str\' = \'\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.capabilities.legacy_shims.legacy_removed_tool",
            rpc_method="release_document_lock",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_acquire_b",
        ),
        ToolEntry(
            name="update_document_lock",
            docstring='Update bounded task/progress metadata without changing authority.\n\nState, heartbeat, dirty status, errors, and mutation revisions remain\nserver-owned and cannot be supplied through this tool.',
            signature="(ctx: 'Context', selector: 'DocumentSelectorInput', task_description: 'str' = '', progress_detail: 'str' = '') -> 'CallToolResult'",
            operation_path="freecad_mcp.capabilities.legacy_shims.legacy_removed_tool",
            rpc_method="update_document_lock",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_acquire_b",
        ),
        ToolEntry(
            name="finalize_document_edit",
            docstring='Validate, Save/Save As, reopen-verify, then CAS-release the lease.\n\nAny validation, save, or sidecar-removal failure retains a visible locked\nerror/recovery record instead of presenting a clean release.',
            signature='(ctx: \'Context\', selector: \'DocumentSelectorInput\', save_mode: "Literal[\'save\', \'save_as\', \'first_save\']" = \'save\', destination: \'str\' = \'\', overwrite: \'bool\' = False, expected_destination_sha256: \'str\' = \'\', validation_profile: \'str\' = \'default\') -> \'CallToolResult\'',
            operation_path="freecad_mcp.capabilities.gateway_refs.connection:finalize_document_edit",
            rpc_method="finalize_document_edit",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_lifecycle",
        ),
        ToolEntry(
            name="save_document",
            docstring='Compare, save, hash, reopen-verify, and retain the renewable lease.\n\nSelect the open document with ``document_name``,\n``document_session_uuid``, or ``canonical_path``. If more than one field is\nsupplied, every field must identify the same live document.',
            signature="(ctx: 'Context', selector: 'DocumentSelectorInput', validation_profile: 'str' = 'default') -> 'CallToolResult'",
            operation_path="freecad_mcp.capabilities.gateway_refs.connection:save_document",
            rpc_method="save_document",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_lifecycle",
        ),
        ToolEntry(
            name="save_document_as",
            docstring='Pre-lock, Save As, hash, reopen-verify, and migrate lease aliases.\n\nSelect the open document with ``document_name``,\n``document_session_uuid``, or ``canonical_path``. If more than one field is\nsupplied, every field must identify the same live document.',
            signature="(ctx: 'Context', selector: 'DocumentSelectorInput', destination: 'str', overwrite: 'bool' = False, expected_destination_sha256: 'str' = '', validation_profile: 'str' = 'default') -> 'CallToolResult'",
            operation_path="freecad_mcp.capabilities.gateway_refs.connection:save_document_as",
            rpc_method="save_document_as",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.LEASE,
            register_module="tools_lease_lifecycle",
        ),
    ),
)
