"""Persistence and migration for the FreeCAD MCP addon settings.

This module is deliberately the single settings implementation used by both
the workbench commands and the XML-RPC server.  Older releases duplicated the
defaults in ``rpc_server.py`` which made isolated profiles especially easy to
misconfigure.
"""

import json
import ipaddress
import os
import secrets
import tempfile
import uuid
from pathlib import Path

import FreeCAD


_SETTINGS_FILENAME = "freecad_mcp_settings.json"

LEASE_MODE_OFF = "off"
LEASE_MODE_OBSERVE = "observe"
LEASE_MODE_ENFORCE = "enforce"
LEASE_MODES = frozenset({LEASE_MODE_OFF, LEASE_MODE_OBSERVE, LEASE_MODE_ENFORCE})


class SettingsPolicyError(ValueError):
    """The persisted configuration is unsafe or internally inconsistent."""


DEFAULT_SETTINGS = {
    "remote_enabled": False,
    "allowed_ips": "127.0.0.1",
    "auto_start_rpc": False,
    "rpc_port": 9875,
    "rpc_bind_host": "127.0.0.1",
    "freecadcmd_path": "",
    "allow_remote_execute_code": False,
    # Stable per-profile identity; empty on the default profile. The isolated
    # setup writes a unique value that a client can pin via --instance-id.
    "instance_id": "",
    # V2 identities/authentication.  The profile id persists, while the
    # runtime id is generated by the running addon and is never saved here.
    "profile_instance_id": "",
    "auth_secret_file": "",
    # New ordinary profiles begin in observe mode. Existing settings files are
    # migrated from their two legacy booleans, preserving an explicit off
    # policy instead of silently strengthening it.
    "document_lease_mode": LEASE_MODE_OBSERVE,
    "allow_network_sidecar": False,
    # Task descriptions may contain sensitive prompt/customer data. Keep them
    # process-local unless an administrator explicitly opts into a sanitized,
    # bounded sidecar summary.
    "persist_task_summary_in_sidecar": False,
    "allow_unsafe_mutating_execute_code": False,
    "allow_authenticated_remote_without_transport_security": False,
    # Compatibility mirrors of document_lease_mode.  New ordinary profiles
    # start in observe mode; existing files without the new key are migrated
    # from these values.
    "enable_document_lock": True,
    "document_lock_enforcement": False,
}

# Backwards-compatible private name used by a few out-of-tree addons.
_DEFAULT_SETTINGS = DEFAULT_SETTINGS


def _get_settings_path():
    return os.path.join(FreeCAD.getUserAppDataDir(), _SETTINGS_FILENAME)


def get_settings_path():
    """Return the active profile's settings path."""
    return _get_settings_path()


def _migrate(settings):
    """Return a migrated copy without silently strengthening old profiles."""
    result = dict(settings) if isinstance(settings, dict) else {}
    if not result.get("rpc_bind_host"):
        result["rpc_bind_host"] = (
            "0.0.0.0" if result.get("remote_enabled", False) else "127.0.0.1"
        )
    has_explicit_mode = "document_lease_mode" in result
    mode = result.get("document_lease_mode")
    if has_explicit_mode and mode not in LEASE_MODES:
        raise SettingsPolicyError(
            "document_lease_mode must be one of: enforce, observe, off"
        )
    if not has_explicit_mode:
        for legacy_key in (
            "enable_document_lock",
            "document_lock_enforcement",
        ):
            if legacy_key in result and not isinstance(result[legacy_key], bool):
                raise SettingsPolicyError(f"{legacy_key} must be true or false")
        enabled = bool(result.get("enable_document_lock", False))
        enforced = bool(result.get("document_lock_enforcement", False))
        if enabled and enforced:
            mode = LEASE_MODE_ENFORCE
        elif enabled:
            mode = LEASE_MODE_OBSERVE
        else:
            mode = LEASE_MODE_OFF
        result["document_lease_mode"] = mode

    # Preserve the old keys while v1 clients exist.  They are derived from the
    # explicit mode so all code paths see one coherent policy.
    result["enable_document_lock"] = mode != LEASE_MODE_OFF
    result["document_lock_enforcement"] = mode == LEASE_MODE_ENFORCE
    if not result.get("profile_instance_id") and result.get("instance_id"):
        result["profile_instance_id"] = result["instance_id"]
    if not result.get("instance_id") and result.get("profile_instance_id"):
        result["instance_id"] = result["profile_instance_id"]
    return result


def _with_defaults(settings):
    result = _migrate(settings)
    for key, value in DEFAULT_SETTINGS.items():
        result.setdefault(key, value)
    return result


def _validate_settings(settings):
    """Validate security-sensitive types without coercing truthy strings."""

    result = _with_defaults(settings)
    boolean_keys = (
        "remote_enabled",
        "auto_start_rpc",
        "allow_remote_execute_code",
        "allow_network_sidecar",
        "persist_task_summary_in_sidecar",
        "allow_unsafe_mutating_execute_code",
        "allow_authenticated_remote_without_transport_security",
        "enable_document_lock",
        "document_lock_enforcement",
    )
    for key in boolean_keys:
        if not isinstance(result.get(key), bool):
            raise SettingsPolicyError(f"{key} must be true or false")

    port = result.get("rpc_port")
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise SettingsPolicyError("rpc_port must be an integer between 1 and 65535")
    host = result.get("rpc_bind_host")
    if (
        not isinstance(host, str)
        or not host.strip()
        or len(host.strip()) > 255
        or any(ord(character) < 32 for character in host)
    ):
        raise SettingsPolicyError("rpc_bind_host is invalid")
    result["rpc_bind_host"] = host.strip()

    profile_id = result.get("profile_instance_id") or result.get("instance_id")
    if profile_id and not isinstance(profile_id, str):
        raise SettingsPolicyError("profile_instance_id must be a string")
    if result["document_lease_mode"] == LEASE_MODE_ENFORCE and profile_id:
        try:
            uuid.UUID(profile_id)
        except (ValueError, AttributeError) as exc:
            raise SettingsPolicyError(
                "enforce mode profile_instance_id must be a UUID"
            ) from exc
    for key in ("allowed_ips", "freecadcmd_path", "auth_secret_file"):
        if not isinstance(result.get(key), str):
            raise SettingsPolicyError(f"{key} must be a string")
    return result


def _fail_closed_settings(message):
    """Return a non-startable policy after malformed persisted configuration."""

    result = dict(DEFAULT_SETTINGS)
    result.update(
        {
            "auto_start_rpc": False,
            "remote_enabled": False,
            "rpc_bind_host": "127.0.0.1",
            "document_lease_mode": LEASE_MODE_ENFORCE,
            "enable_document_lock": True,
            "document_lock_enforcement": True,
            "_configuration_error": str(message)[:512],
        }
    )
    return result


def is_loopback_host(host):
    """Return true only for an unambiguous loopback address/name."""

    if not isinstance(host, str):
        return False
    normalized = host.strip().lower().rstrip(".")
    if normalized == "localhost":
        return True
    if normalized.startswith("[") and normalized.endswith("]"):
        normalized = normalized[1:-1]
    try:
        address = ipaddress.ip_address(normalized)
    except ValueError:
        return False
    if address.is_loopback:
        return True
    mapped = getattr(address, "ipv4_mapped", None)
    return bool(mapped is not None and mapped.is_loopback)


def resolve_rpc_bind_host(settings):
    """Resolve the effective bind host and enforce the transport policy."""

    current = _validate_settings(settings)
    if not current["remote_enabled"]:
        return "127.0.0.1"
    host = current["rpc_bind_host"]
    if (
        current["document_lease_mode"] == LEASE_MODE_ENFORCE
        and not is_loopback_host(host)
        and not current["allow_authenticated_remote_without_transport_security"]
    ):
        raise SettingsPolicyError(
            "enforce mode refuses a plain non-loopback RPC bind; keep the addon "
            "on loopback behind an SSH/TLS tunnel or explicitly enable the unsafe override"
        )
    return host


def _atomic_write_settings(path, settings):
    parent = os.path.dirname(path)
    os.makedirs(parent, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=_SETTINGS_FILENAME + ".", dir=parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(settings, f, indent=2, sort_keys=True)
            f.write("\n")
            f.flush()
            os.fsync(f.fileno())
        try:
            os.chmod(temporary, 0o600)
        except OSError:
            pass
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def load_settings():
    path = _get_settings_path()
    if os.path.exists(path):
        try:
            with open(path, "r") as f:
                settings = json.load(f)
            if not isinstance(settings, dict):
                raise SettingsPolicyError("settings root must be a JSON object")
            needs_mode_migration = "document_lease_mode" not in settings
            validated = _validate_settings(settings)
            if needs_mode_migration:
                try:
                    _atomic_write_settings(path, validated)
                except Exception as exc:
                    FreeCAD.Console.PrintWarning(
                        f"Loaded but could not persist MCP lease-mode migration: {exc}\n"
                    )
            return validated
        except Exception as e:
            FreeCAD.Console.PrintWarning(f"Failed to load MCP settings: {e}\n")
            return _fail_closed_settings(e)
    return _validate_settings(DEFAULT_SETTINGS)


def save_settings(settings):
    path = _get_settings_path()
    try:
        if not isinstance(settings, dict) or settings.get("_configuration_error"):
            raise SettingsPolicyError(
                "refusing to overwrite an invalid settings file; repair it explicitly"
            )
        settings = _validate_settings(settings)
        _atomic_write_settings(path, settings)
    except Exception as e:
        FreeCAD.Console.PrintError(f"Failed to save MCP settings: {e}\n")


def ensure_profile_secret(settings=None):
    """Create the per-profile 256-bit authentication secret when configured.

    The function returns ``(settings, secret_path)`` and never exposes the
    secret value.  It is intentionally invoked by isolated-profile setup or by
    an explicit administrator action, not merely by importing the addon.
    """
    current = _migrate(settings or load_settings())
    configured_secret = current.get("auth_secret_file")
    secret_path = Path(
        configured_secret
        or os.path.join(FreeCAD.getUserAppDataDir(), "freecad_mcp_auth.secret")
    )
    created = False
    if not secret_path.exists():
        secret_path.parent.mkdir(parents=True, exist_ok=True)
        flags = os.O_CREAT | os.O_EXCL | os.O_WRONLY
        if hasattr(os, "O_BINARY"):
            flags |= os.O_BINARY
        fd = os.open(secret_path, flags, 0o600)
        try:
            os.write(fd, secrets.token_bytes(32))
            os.fsync(fd)
        finally:
            os.close(fd)
        created = True
    try:
        from document_lease.sidecar import _harden_permissions
    except ImportError:
        from addon.FreeCADMCP.document_lease.sidecar import _harden_permissions

    # Enforce the same POSIX mode/Windows owner-only DACL policy as lease
    # sidecars. Authentication must not start with a broadly readable profile
    # secret, including an existing secret selected by an administrator.
    try:
        _harden_permissions(secret_path, strict=True)
    except Exception:
        if created:
            try:
                os.unlink(secret_path)
            except OSError:
                pass
        raise
    current["auth_secret_file"] = str(secret_path)
    save_settings(current)
    return current, str(secret_path)
