"""Capability manifest for parametric (bootstrapped)."""

from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="parametric",
    register_modules=('tools_parametric_body', 'tools_parametric_sheet_a', 'tools_parametric_sheet_b'),
    tools=(
        ToolEntry(
            name="body_create",
            docstring='Create a PartDesign::Body.\n\nRecommended pattern: Body → Sketch on XY_Plane → Pad → Pocket.',
            signature="(ctx: 'Context', doc_name: 'str', body_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.body_create_operation",
            rpc_method="body_create",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_body",
        ),
        ToolEntry(
            name="body_set_tip",
            docstring="Set a Body's Tip to a feature (keeps the PartDesign history tip correct).",
            signature="(ctx: 'Context', doc_name: 'str', body_name: 'str', feature_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.body_set_tip_operation",
            rpc_method="body_set_tip",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_body",
        ),
        ToolEntry(
            name="diagnose_parametric",
            docstring='Diagnose parametric / expression / sketch issues.\n\nReports invalid objects, expression bind issues, and sketch constraint\nconflict/redundant/malformed summaries. Scope to one object or the whole doc.',
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.diagnose_parametric_operation",
            rpc_method="diagnose_parametric",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_parametric_body",
        ),
        ToolEntry(
            name="get_sketch_diagnostics",
            docstring='Return solver diagnostics for a Sketcher sketch.\n\nCall this before pad_feature to verify the sketch is fully constrained and\nclosed. Returns degrees of freedom, constraint counts, conflicting /\nredundant constraint indices, solver message, and whether the sketch wire\nis closed.\n\nArgs:\n    doc_name: The document containing the sketch.\n    sketch_name: Name of the sketch to inspect.\n\nReturns:\n    JSON dict with:\n    - geometry_count: number of geometry elements\n    - constraint_count: number of constraints\n    - state: object state flags (e.g. [\'Up-to-date\'])\n    - conflicting_constraints: list of conflicting constraint indices\n    - redundant_constraints: list of redundant constraint indices\n    - malformed_constraints: list of malformed constraint indices\n    - solver_message: solver status string (if available)\n    - is_closed: whether the sketch wire forms a closed profile\n\nExamples:\n    ```json\n    {"doc_name": "Part", "sketch_name": "Sketch"}\n    ```',
            signature="(ctx: 'Context', doc_name: 'str', sketch_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_sketch_diagnostics_operation",
            rpc_method="get_sketch_diagnostics",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_parametric_body",
        ),
        ToolEntry(
            name="sketch_attach",
            docstring='Attach a sketch to an origin plane or face support.\n\n``support`` may be:\n- ``"XY_Plane"`` / ``"XZ_Plane"`` / ``"YZ_Plane"``\n- ``"ObjectName:FaceN"``\n- ``{"object": "Obj", "subname": "Face1"}``\n\n``attachment_offset`` is optional and uses the same Placement dict form as\n``edit_object`` / ``get_object``. ``Rotation.Angle`` is in **degrees**.\nPrefer this over rotating ``Placement`` on a deactivated attachment (P3 trap).',
            signature="(ctx: 'Context', doc_name: 'str', sketch_name: 'str', support: 'Any', attachment_offset: 'dict[str, Any] | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.sketch_attach_operation",
            rpc_method="sketch_attach",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_body",
        ),
        ToolEntry(
            name="sketch_edit_constraint",
            docstring='Edit a dimensional constraint by stable ``name`` (preferred) or index.\n\nAfter trim/fillet, geo indices shift — always prefer ``name``.',
            signature="(ctx: 'Context', doc_name: 'str', sketch_name: 'str', value: 'float | None' = None, name: 'str | None' = None, index: 'int | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.sketch_edit_constraint_operation",
            rpc_method="sketch_edit_constraint",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_body",
        ),
        ToolEntry(
            name="spreadsheet_create",
            docstring='Create a Spreadsheet::Sheet for parametric dimensions.\n\nRecipe: create sheet → set cells/aliases → bind sketch constraints and\nPad/Pocket Length via ``set_expression`` using ``<<Sheet>>.Alias``.\n\nArgs:\n    doc_name: Document to create the sheet in.\n    sheet_name: Name for the new spreadsheet object (e.g. ``Dims``).',
            signature="(ctx: 'Context', doc_name: 'str', sheet_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.spreadsheet_create_operation",
            rpc_method="spreadsheet_create",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_sheet_a",
        ),
        ToolEntry(
            name="spreadsheet_get_cells",
            docstring='Read spreadsheet cell contents and evaluated values.\n\n``addresses`` entries may be address strings (``A1``) or dicts with\n``address`` / ``alias``.',
            signature="(ctx: 'Context', doc_name: 'str', sheet_name: 'str', addresses: 'list[Any]') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.spreadsheet_get_cells_operation",
            rpc_method="spreadsheet_get_cells",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_sheet_a",
        ),
        ToolEntry(
            name="spreadsheet_set_alias",
            docstring='Set a spreadsheet cell alias (e.g. A1 → Wall).',
            signature="(ctx: 'Context', doc_name: 'str', sheet_name: 'str', address: 'str', alias: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.spreadsheet_set_alias_operation",
            rpc_method="spreadsheet_set_alias",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_sheet_a",
        ),
        ToolEntry(
            name="spreadsheet_set_cells",
            docstring='Set spreadsheet cell values (and optional aliases) in batch.\n\nEach cell dict accepts:\n- ``address`` (e.g. ``A1``) and/or ``alias`` to resolve an existing alias\n- ``value`` — number or formula string\n- ``alias`` with ``address`` — also sets the alias on that address\n- ``set_alias`` — set alias when addressing by address alone\n\nArgs:\n    doc_name: Document containing the sheet.\n    sheet_name: Spreadsheet object name.\n    cells: List of cell update dicts.',
            signature="(ctx: 'Context', doc_name: 'str', sheet_name: 'str', cells: 'list[dict[str, Any]]') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.spreadsheet_set_cells_operation",
            rpc_method="spreadsheet_set_cells",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_sheet_a",
        ),
        ToolEntry(
            name="clear_expression",
            docstring='Clear an expression binding on an object property.',
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str', prop_path: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.clear_expression_operation",
            rpc_method="clear_expression",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_sheet_b",
        ),
        ToolEntry(
            name="list_expressions",
            docstring='List ExpressionEngine bindings on an object.',
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.list_expressions_operation",
            rpc_method="list_expressions",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_parametric_sheet_b",
        ),
        ToolEntry(
            name="set_expression",
            docstring='Bind a FreeCAD expression to an object property.\n\nCommon ``prop_path`` values:\n- Sketch dimensional constraints: ``Constraints[3]``\n- Pad/Pocket: ``Length``, ``Length2``\n\nExpression examples: ``<<Dims>>.Wall``, ``<<Dims>>.PadH``.\n\nReturns structured JSON; on parse/bind failure returns an error (not a\nsilent Invalid object).',
            signature="(ctx: 'Context', doc_name: 'str', object_name: 'str', prop_path: 'str', expression: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.set_expression_operation",
            rpc_method="set_expression",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_sheet_b",
        ),
        ToolEntry(
            name="spreadsheet_list_aliases",
            docstring='List all aliases on a spreadsheet as ``{alias: address}``.',
            signature="(ctx: 'Context', doc_name: 'str', sheet_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.spreadsheet_list_aliases_operation",
            rpc_method="spreadsheet_list_aliases",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_parametric_sheet_b",
        ),
    ),
)
