"""Capability manifest for io (bootstrapped)."""

from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="io",
    register_modules=('tools_io_export', 'tools_io_import'),
    tools=(
        ToolEntry(
            name="export_brep",
            docstring='Export a shape to a BREP file (OpenCASCADE native format).\n\nBREP preserves exact geometry and is lossless for round-tripping.\n\nArgs:\n    doc_name: Document containing the shape.\n    obj_name: Name of the shape object to export.\n    file_path: Absolute path to the output BREP file.\n\nReturns:\n    JSON confirming success and the file path.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str', file_path: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.export_brep_operation",
            rpc_method="export_brep",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_io_export",
        ),
        ToolEntry(
            name="export_step",
            docstring='Export shapes to a STEP file.\n\nArgs:\n    doc_name: Document containing the shapes.\n    file_path: Absolute path to the output STEP file.\n    obj_names: Optional list of object names to export. If omitted,\n        all objects with a Shape are exported.\n\nReturns:\n    JSON with the count of exported objects and the file path.',
            signature="(ctx: 'Context', doc_name: 'str', file_path: 'str', obj_names: 'list[str] | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.export_step_operation",
            rpc_method="export_step",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_io_export",
        ),
        ToolEntry(
            name="export_stl",
            docstring='Export shapes to an STL file (tessellated mesh).\n\nArgs:\n    doc_name: Document containing the shapes.\n    file_path: Absolute path to the output STL file.\n    obj_names: Optional list of object names. If omitted, all shapes exported.\n    mesh_deviation: Tessellation accuracy in mm (smaller = finer, default 0.1).\n\nReturns:\n    JSON with the count of exported objects, facet count, and file path.',
            signature="(ctx: 'Context', doc_name: 'str', file_path: 'str', obj_names: 'list[str] | None' = None, mesh_deviation: 'float' = 0.1) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.export_stl_operation",
            rpc_method="export_stl",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_io_export",
        ),
        ToolEntry(
            name="get_document_tree",
            docstring='Return a compact document/container tree.\n\nArgs:\n    doc_name: Document to inspect.\n    root_filter: Optional Name/Label substring used to select tree roots.\n    max_depth: Maximum container depth to include.\n    include: Fields to include, defaulting to Name/Label/TypeId/Visibility/State.\n    include_properties: Optional object properties to include.\n    selected_nodes: Names/labels whose properties should be included.\n\nReturns:\n    JSON tree for compact agent inspection.',
            signature="(ctx: 'Context', doc_name: 'str', root_filter: 'str | None' = None, max_depth: 'int' = 4, include: 'list[str] | None' = None, include_properties: 'list[str] | None' = None, selected_nodes: 'list[str] | None' = None) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_document_tree_operation",
            rpc_method="get_document_tree",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_io_export",
        ),
        ToolEntry(
            name="set_color",
            docstring='Set the display colour and transparency of an object.\n\nArgs:\n    doc_name: Document containing the object.\n    obj_name: Name of the object.\n    r: Red channel 0.0-1.0.\n    g: Green channel 0.0-1.0.\n    b: Blue channel 0.0-1.0.\n    transparency: Transparency 0.0 (opaque) - 1.0 (fully transparent).\n\nReturns:\n    Success message and a screenshot.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str', r: 'float', g: 'float', b: 'float', transparency: 'float' = 0.0) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.set_color_operation",
            rpc_method="set_color",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_io_export",
        ),
        ToolEntry(
            name="import_brep",
            docstring='Import a BREP file into an existing FreeCAD document.\n\nArgs:\n    doc_name: Target document name.\n    file_path: Absolute path to the BREP file to import.\n    obj_name: Name for the imported Part::Feature object.\n\nReturns:\n    JSON confirming success and the object name.',
            signature="(ctx: 'Context', doc_name: 'str', file_path: 'str', obj_name: 'str' = 'BRepImport') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.import_brep_operation",
            rpc_method="import_brep",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_io_import",
        ),
        ToolEntry(
            name="import_step",
            docstring='Import a STEP file into an existing FreeCAD document.\n\nArgs:\n    doc_name: Target document name.\n    file_path: Absolute path to the STEP file to import.\n\nReturns:\n    JSON confirming success and the file path.',
            signature="(ctx: 'Context', doc_name: 'str', file_path: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.import_step_operation",
            rpc_method="import_step",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_io_import",
        ),
    ),
)
