"""Capability manifest for measure (bootstrapped)."""

from __future__ import annotations

from ..schema import ExecutionMode, MutationClass, SubjectManifest, ToolEntry

MANIFEST = SubjectManifest(
    subject="measure",
    register_modules=('tools_measure_a', 'tools_measure_b'),
    tools=(
        ToolEntry(
            name="bounding_box",
            docstring='Return the world-frame axis-aligned bounding box of a shape.\n\nLink-safe: follows ``App::Link`` to the linked solid when needed and applies\n``getGlobalPlacement()`` once (no Placement double-counting).\n\nArgs:\n    doc_name: Document containing the object.\n    obj_name: Name of the shape object or Link.\n\nReturns:\n    JSON with xmin/ymin/zmin/xmax/ymax/zmax, dx/dy/dz, and shape-source metadata.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.bounding_box_operation",
            rpc_method="bounding_box",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_measure_a",
        ),
        ToolEntry(
            name="measure_angle",
            docstring='Measure the angle between two edges or objects.\n\nRefs can be ``"ObjectName"`` or ``"ObjectName:EdgeN"`` (e.g. ``"Box:Edge1"``).\n\nArgs:\n    doc_name: Document containing the objects.\n    edge1_ref: First edge reference.\n    edge2_ref: Second edge reference.\n\nReturns:\n    JSON with ``angle_deg`` in degrees.',
            signature="(ctx: 'Context', doc_name: 'str', edge1_ref: 'str', edge2_ref: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.measure_angle_operation",
            rpc_method="measure_angle",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_measure_a",
        ),
        ToolEntry(
            name="measure_area",
            docstring='Measure the total surface area of a shape.\n\nArgs:\n    doc_name: Document containing the object.\n    obj_name: Name of the shape object.\n\nReturns:\n    JSON with ``area_mm2`` and ``area_cm2``.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.measure_area_operation",
            rpc_method="measure_area",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_measure_a",
        ),
        ToolEntry(
            name="measure_distance",
            docstring='Measure the minimum distance between two shapes.\n\nArgs:\n    doc_name: Document containing both shapes.\n    shape1_ref: Name of the first shape object.\n    shape2_ref: Name of the second shape object.\n\nReturns:\n    JSON with ``distance`` in mm.',
            signature="(ctx: 'Context', doc_name: 'str', shape1_ref: 'str', shape2_ref: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.measure_distance_operation",
            rpc_method="measure_distance",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_measure_a",
        ),
        ToolEntry(
            name="measure_volume",
            docstring='Measure the volume of a solid shape.\n\nArgs:\n    doc_name: Document containing the object.\n    obj_name: Name of the shape object.\n\nReturns:\n    JSON with ``volume_mm3`` and ``volume_cm3``.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.measure_volume_operation",
            rpc_method="measure_volume",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_measure_a",
        ),
        ToolEntry(
            name="center_of_mass",
            docstring='Compute the centre of mass of a solid shape.\n\nArgs:\n    doc_name: Document containing the object.\n    obj_name: Name of the shape object.\n\nReturns:\n    JSON with ``x``, ``y``, ``z`` coordinates in mm.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.center_of_mass_operation",
            rpc_method="center_of_mass",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_measure_b",
        ),
        ToolEntry(
            name="common_volume_along_path",
            docstring="Sweep a moving solid along a path and report common volumes with obstacles.\n\nProvide either:\n- ``path_object`` + ``sample_count`` to sample a wire/edge path, or\n- ``samples`` as ``[{x,y,z, yaw_deg?}, ...]`` world positions for the moving\n  object's global placement origin.\n\nRuns read-only in the isolated worker.\n\nArgs:\n    doc_name: Document containing the objects.\n    moving_object: Object/Link that moves along the path.\n    obstacle_objects: Objects/Links to intersect against.\n    path_object: Optional wire/edge object to sample.\n    sample_count: Samples along ``path_object`` (ignored when ``samples`` is set).\n    samples: Explicit world-space sample points.\n    volume_threshold_mm3: Minimum common volume counted as a collision.\n    stop_on_first_hit: Stop sampling after the first colliding sample.\n\nReturns:\n    JSON with per-sample common volumes and collision flags.",
            signature="(ctx: 'Context', doc_name: 'str', moving_object: 'str', obstacle_objects: 'list[str]', path_object: 'str | None' = None, sample_count: 'int' = 12, samples: 'list[dict[str, Any]] | None' = None, volume_threshold_mm3: 'float' = 1e-06, stop_on_first_hit: 'bool' = False) -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.common_volume_along_path_operation",
            rpc_method="common_volume_along_path",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.MUTATION,
            register_module="tools_measure_b",
        ),
        ToolEntry(
            name="get_global_shape",
            docstring='Resolve a world-frame shape summary for solids and App::Link objects.\n\nUse this when you need bbox/volume/COM without baking Placement twice.\nFollows broken/null Link proxy shapes to ``LinkedObject`` when possible.\n\nArgs:\n    doc_name: Document containing the object.\n    obj_name: Object or Link name.\n\nReturns:\n    JSON with frame=world metrics, bbox, volume, COM, and placement metadata.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.get_global_shape_operation",
            rpc_method="get_global_shape",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_measure_b",
        ),
        ToolEntry(
            name="validate_geometry",
            docstring='Validate the geometry of a shape and return diagnostic information.\n\nChecks whether the shape is null, valid, closed, and reports face/edge/vertex\ncounts along with a BRep analysis result.\n\nArgs:\n    doc_name: Document containing the object.\n    obj_name: Name of the shape object.\n\nReturns:\n    JSON with validity flags, counts, volume/area, and BRep analysis output.',
            signature="(ctx: 'Context', doc_name: 'str', obj_name: 'str') -> 'CallToolResult'",
            operation_path="freecad_mcp.operations.validate_geometry_operation",
            rpc_method="validate_geometry",
            execution_mode=ExecutionMode.TYPED_GATEWAY,
            gui_thread=False,
            mutation_class=MutationClass.READ,
            register_module="tools_measure_b",
        ),
    ),
)
