from .core import (
    close_document_operation,
    create_document_operation,
    create_object_operation,
    delete_object_operation,
    edit_object_operation,
    execute_code_operation,
    get_object_operation,
    get_objects_operation,
    get_parts_list_operation,
    get_recompute_log_operation,
    get_sketch_diagnostics_operation,
    get_view_operation,
    insert_part_from_library_operation,
    list_documents_operation,
    sketch_create_operation,
    sketch_add_geometry_operation,
    sketch_add_constraint_operation,
    sketch_add_line_operation,
    sketch_add_circle_operation,
    sketch_add_arc_operation,
    sketch_add_rectangle_operation,
    sketch_constrain_coincident_operation,
    sketch_constrain_horizontal_operation,
    sketch_constrain_vertical_operation,
    sketch_constrain_distance_operation,
    sketch_constrain_radius_operation,
    sketch_constrain_equal_operation,
    sketch_constrain_parallel_operation,
    sketch_constrain_perpendicular_operation,
    sketch_constrain_tangent_operation,
    pad_feature_operation,
    pocket_feature_operation,
    linear_pattern_feature_operation,
    polar_pattern_feature_operation,
    mirror_feature_operation,
    create_spur_gear_operation,
    recompute_document_operation,
    undo_operation,
    redo_operation,
)

# P1 — Sketch curves
from .p1_curves import (
    sketch_add_polyline_operation,
    sketch_add_bspline_operation,
    sketch_add_bspline_through_points_operation,
    sketch_add_bezier_operation,
    sketch_add_ellipse_operation,
    sketch_add_arc_of_ellipse_operation,
    sketch_add_slot_operation,
    sketch_add_regular_polygon_operation,
    sketch_add_parametric_curve_operation,
    sketch_import_points_operation,
    sketch_toggle_construction_operation,
)

# P2 — Sketch editing
from .p2_editing import (
    sketch_trim_operation,
    sketch_extend_operation,
    sketch_split_operation,
    sketch_fillet_operation,
    sketch_offset_operation,
    sketch_symmetry_operation,
)

# P3 — 3-D features
from .p3_features import (
    revolve_feature_operation,
    loft_feature_operation,
    sweep_feature_operation,
    helical_sweep_feature_operation,
    fillet_feature_operation,
    chamfer_feature_operation,
    boolean_union_operation,
    boolean_difference_operation,
    boolean_intersection_operation,
)

# P4 — Gear library
from .p4_gears import (
    create_involute_gear_operation,
    create_helical_gear_operation,
    compute_gear_geometry_operation,
    check_gear_pair_operation,
)

# P5 — Measurement & transforms
from .p5_measure import (
    measure_distance_operation,
    measure_angle_operation,
    measure_area_operation,
    measure_volume_operation,
    bounding_box_operation,
    center_of_mass_operation,
    validate_geometry_operation,
    translate_operation,
    rotate_operation,
    scale_operation,
)

# P6 — IO
from .p6_io import (
    export_step_operation,
    import_step_operation,
    export_stl_operation,
    export_brep_operation,
    import_brep_operation,
    set_color_operation,
)

# P7 - Assembly references, sketch geometry, path wires
from .p7_assembly import (
    build_path_wire_operation,
    create_assembly_grounded_joint_operation,
    create_assembly_joint_operation,
    create_assembly_operation,
    create_datum_plane_operation,
    create_part_container_operation,
    create_subshape_binder_operation,
    get_document_tree_operation,
    get_sketch_geometry_operation,
    move_object_operation,
    sketch_add_external_projection_operation,
    sweep_pipe_operation,
)

__all__ = [
    # Core
    "close_document_operation",
    "create_document_operation",
    "create_object_operation",
    "delete_object_operation",
    "edit_object_operation",
    "execute_code_operation",
    "get_object_operation",
    "get_objects_operation",
    "get_parts_list_operation",
    "get_recompute_log_operation",
    "get_sketch_diagnostics_operation",
    "get_view_operation",
    "insert_part_from_library_operation",
    "list_documents_operation",
    "sketch_create_operation",
    "sketch_add_geometry_operation",
    "sketch_add_constraint_operation",
    "sketch_add_line_operation",
    "sketch_add_circle_operation",
    "sketch_add_arc_operation",
    "sketch_add_rectangle_operation",
    "sketch_constrain_coincident_operation",
    "sketch_constrain_horizontal_operation",
    "sketch_constrain_vertical_operation",
    "sketch_constrain_distance_operation",
    "sketch_constrain_radius_operation",
    "sketch_constrain_equal_operation",
    "sketch_constrain_parallel_operation",
    "sketch_constrain_perpendicular_operation",
    "sketch_constrain_tangent_operation",
    "pad_feature_operation",
    "pocket_feature_operation",
    "linear_pattern_feature_operation",
    "polar_pattern_feature_operation",
    "mirror_feature_operation",
    "create_spur_gear_operation",
    "recompute_document_operation",
    "undo_operation",
    "redo_operation",
    # P1
    "sketch_add_polyline_operation",
    "sketch_add_bspline_operation",
    "sketch_add_bspline_through_points_operation",
    "sketch_add_bezier_operation",
    "sketch_add_ellipse_operation",
    "sketch_add_arc_of_ellipse_operation",
    "sketch_add_slot_operation",
    "sketch_add_regular_polygon_operation",
    "sketch_add_parametric_curve_operation",
    "sketch_import_points_operation",
    "sketch_toggle_construction_operation",
    # P2
    "sketch_trim_operation",
    "sketch_extend_operation",
    "sketch_split_operation",
    "sketch_fillet_operation",
    "sketch_offset_operation",
    "sketch_symmetry_operation",
    # P3
    "revolve_feature_operation",
    "loft_feature_operation",
    "sweep_feature_operation",
    "helical_sweep_feature_operation",
    "fillet_feature_operation",
    "chamfer_feature_operation",
    "boolean_union_operation",
    "boolean_difference_operation",
    "boolean_intersection_operation",
    # P4
    "create_involute_gear_operation",
    "create_helical_gear_operation",
    "compute_gear_geometry_operation",
    "check_gear_pair_operation",
    # P5
    "measure_distance_operation",
    "measure_angle_operation",
    "measure_area_operation",
    "measure_volume_operation",
    "bounding_box_operation",
    "center_of_mass_operation",
    "validate_geometry_operation",
    "translate_operation",
    "rotate_operation",
    "scale_operation",
    # P6
    "export_step_operation",
    "import_step_operation",
    "export_stl_operation",
    "export_brep_operation",
    "import_brep_operation",
    "set_color_operation",
    # P7
    "build_path_wire_operation",
    "create_assembly_grounded_joint_operation",
    "create_assembly_joint_operation",
    "create_assembly_operation",
    "create_datum_plane_operation",
    "create_part_container_operation",
    "create_subshape_binder_operation",
    "get_document_tree_operation",
    "get_sketch_geometry_operation",
    "move_object_operation",
    "sketch_add_external_projection_operation",
    "sweep_pipe_operation",
]
